import { Theme } from '@/core/theme/types';
import { StyleSheet } from 'react-native';

export const resetPasswordStyles = (theme: Theme) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.colors.background },
    container: { flex: 1 },
    scrollContent: { padding: 24, paddingTop: 60 },
    iconWrapper: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginBottom: 20,
    },
    title: {
      fontSize: 26,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      textAlign: 'center',
      marginBottom: 8,
    },
    subtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 20,
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.colors.errorLight,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.error,
    },
    errorBannerText: { color: theme.colors.error, fontSize: 13, flex: 1 },
    form: { marginTop: 4 },
    label: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
      marginBottom: 6,
    },
    labelSpacing: { marginTop: 16 },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 12,
      marginBottom: 4,
    },
    inputIcon: { marginRight: 10 },
    input: {
      flex: 1,
      paddingVertical: 13,
      fontSize: 15,
      color: theme.colors.textPrimary,
    },
    eyeButton: { padding: 6 },
    inputError: {
      borderColor: theme.colors.error,
      backgroundColor: theme.colors.errorLight,
    },
    errorText: {
      color: theme.colors.error,
      fontSize: 12,
      marginBottom: 8,
      marginTop: 2,
    },
    rulesCard: {
      backgroundColor: theme.colors.backgroundLight,
      borderRadius: 8,
      padding: 12,
      marginTop: 8,
      marginBottom: 4,
      gap: 6,
    },
    ruleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
    },
    ruleText: {
      fontSize: 12,
      color: theme.colors.textMuted,
    },
    matchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
      marginBottom: 4,
    },
    primaryButton: {
      marginTop: 24,
      backgroundColor: theme.colors.primary,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 8,
    },
    primaryButtonText: {
      color: theme.colors.white,
      fontWeight: '700',
      fontSize: 16,
    },
    disabledButton: { opacity: 0.6 },
    backLink: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      marginTop: 16,
    },
    backLinkText: {
      color: theme.colors.link,
      fontSize: 13,
      fontWeight: '500',
    },
    successContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 32,
    },
    successIconWrapper: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: theme.colors.successLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
    },
    successTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      textAlign: 'center',
      marginBottom: 10,
    },
    successSubtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 32,
    },
    confirmBtn: {
      fontSize: 12,
      marginLeft: 5,
    },
    strengthBarView: {
      marginTop: 6,
      marginBottom: 4,
    },
    strengthBarBottom: {
      fontSize: 11,
      marginTop: 4,
      fontWeight: '500',
    },
    strengthHeader: {
      flexDirection: 'row',
      gap: 4,
    },
    strengthBody: {
      flex: 1,
      height: 4,
      borderRadius: 2,
    },
  });
