export enum Country {
  UNITED_STATES = 'united_states',
  INDIA = 'india',
  CHINA = 'china',
  UNITED_KINGDOM = 'united_kingdom',
  CANADA = 'canada',
  AUSTRALIA = 'australia',
  GERMANY = 'germany',
  FRANCE = 'france',
  BRAZIL = 'brazil',
  JAPAN = 'japan',
  RUSSIA = 'russia',
  SOUTH_AFRICA = 'south_africa',
  ITALY = 'italy',
  SPAIN = 'spain',
  MEXICO = 'mexico',
  NETHERLANDS = 'netherlands',
  SWEDEN = 'sweden',
  SWITZERLAND = 'switzerland',
  NEW_ZEALAND = 'new_zealand',
  SINGAPORE = 'singapore',
  UNITED_ARAB_EMIRATES = 'united_arab_emirates',
  OTHER = 'other',
}
