import { StyleSheet } from 'react-native';

import { Theme } from '@/core/theme/types';

export const notificationStyles = (theme: Theme) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: theme.colors.backgroundPage,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 40,
    },
    detailScrollContent: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 40,
    },
    loadingWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      paddingHorizontal: 24,
    },
    loadingText: {
      fontSize: 13,
      color: theme.colors.textMuted,
    },
    sectionCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 8,
      marginBottom: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      overflow: 'hidden',
      ...theme.shadows.sm,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    sectionIconWrapper: {
      width: 26,
      height: 26,
      borderRadius: 7,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 0,
      flex: 1,
    },
    sectionCount: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.colors.textInverse,
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 8,
      overflow: 'hidden',
    },
    notifItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingHorizontal: 16,
      paddingVertical: 14,
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    notifItemLast: {
      borderBottomWidth: 0,
    },
    notifItemUnread: {
      backgroundColor: theme.colors.primaryLight,
    },
    notifIconWrapper: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: theme.colors.backgroundLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    notifIconWrapperUnread: {
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    notifContent: {
      flex: 1,
      minWidth: 0,
    },
    notifTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 3,
      gap: 8,
    },
    notifTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      flex: 1,
    },
    notifTitleUnread: {
      color: theme.colors.primary,
      fontWeight: '700',
    },
    notifTime: {
      fontSize: 11,
      color: theme.colors.textMuted,
    },
    notifMessage: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      lineHeight: 18,
    },
    unreadDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
      marginTop: 4,
    },
    detailCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      padding: 18,
      gap: 18,
      ...theme.shadows.sm,
    },
    detailHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    detailIconWrapper: {
      width: 52,
      height: 52,
      borderRadius: 8,
      backgroundColor: theme.colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailHeaderText: {
      flex: 1,
      minWidth: 0,
    },
    detailCategory: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 0,
      marginBottom: 4,
    },
    detailTitle: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    detailMessage: {
      fontSize: 15,
      lineHeight: 23,
      color: theme.colors.textSecondary,
    },
    detailMetaList: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.divider,
    },
    detailMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 14,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    detailMetaLabel: {
      fontSize: 13,
      color: theme.colors.textMuted,
      flexShrink: 0,
    },
    detailMetaValue: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      textAlign: 'right',
    },
    detailActionButton: {
      minHeight: 48,
      borderRadius: 8,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
    },
    detailActionText: {
      color: theme.colors.textInverse,
      fontSize: 14,
      fontWeight: '800',
    },
    emptyCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 8,
      padding: 32,
      alignItems: 'center',
      gap: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      ...theme.shadows.sm,
    },
    emptyIconWrapper: {
      width: 64,
      height: 64,
      borderRadius: 8,
      backgroundColor: theme.colors.backgroundLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: 13,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 19,
    },
  });
