export const COLLECTION_NAMES = {
  PERMISSION: 'permissions',
  ROLE: 'roles',
  USER: 'users',
  USER_SESSION: 'user_sessions',

  PROFILE: 'profiles',
  MEDIA: 'media',
  INTERACTION: 'interactions',
  VERIFICATION: 'verifications',

  USER_BLOCK: 'user_blocks',
  USER_PROFILE_HIDE: 'user_profile_hides',
  USER_REPORT: 'user_reports',

  PLAN: 'plans',
  FEATURE: 'features',
  PLAN_FEATURE: 'plan_features',
  SUBSCRIPTION: 'subscriptions',
  LEARNING_BOOST: 'learning_boosts',
  PAYMENT: 'payments',
  PROMOTION_COUPON: 'promotion_coupons',
  PAYMENT_INVOICE: 'payment_invoices',
  WALLET_TRANSACTION: 'wallet_transactions',
  REFERRAL_REWARD: 'referral_rewards',

  ANALYTICS_EVENT: 'analytics_events',
  ANALYTICS_DAILY_SUMMARY: 'analytics_daily_summaries',

  CHAT_ROOM: 'chat_rooms',
  CHAT_MESSAGE: 'chat_messages',

  ACTIVITY_LOG: 'activity_logs',
  ADMIN_AUDIT_LOG: 'admin_audit_logs',

  NOTIFICATION: 'notifications',
  NOTIFICATION_TEMPLATE: 'notification_templates',
  NOTIFICATION_LOG: 'notification_logs',
  NOTIFICATION_DEVICE_TOKEN: 'notification_device_tokens',

  SUPPORT_TICKET: 'support_tickets',

  ACCOUNT_SETTING: 'account_settings',
  PRIVACY_SETTING: 'privacy_settings',
  NOTIFICATION_SETTING: 'notification_settings',
  COMMUNICATION_SETTING: 'communication_settings',
  SECURITY_SETTING: 'security_settings',
  LOCALIZATION_SETTING: 'localization_settings',
  ACCESSIBILITY_SETTING: 'accessibility_settings',
  MEDIA_SETTING: 'media_settings',
  AI_SETTING: 'ai_settings',
  USER_CONSENT: 'user_consents',

  STUDENT_PROFILE: 'student_profiles',
  PARENT_PROFILE: 'parent_profiles',
  PARENT_STUDENT_RELATIONSHIP: 'parent_student_relationships',
  PARENTAL_CONTROL: 'parental_controls',
  STUDENT_ACADEMIC_RECORD: 'student_academic_records',
  SUBJECT: 'subjects',
  STUDENT_SUBJECT_ENROLLMENT: 'student_subject_enrollments',
  LEARNING_SCHEDULE: 'learning_schedules',
  LEARNING_ENTITLEMENT: 'learning_entitlements',
  AI_TUTOR_SESSION: 'ai_tutor_sessions',
  AI_TUTOR_MESSAGE: 'ai_tutor_messages',
  CLASSROOM: 'classrooms',
  CLASSROOM_MESSAGE: 'classroom_messages',
  CLASSROOM_FILE: 'classroom_files',
  TUTOR_PROFILE: 'tutor_profiles',
  TUTOR_AVAILABILITY: 'tutor_availability',
  TUTOR_SESSION_NOTE: 'tutor_session_notes',
  SAFETY_EVENT: 'safety_events',
};
