export const EDUCATION_PLATFORM_MODULE_KEYS = [
  'authentication',
  'users',
  'organizations',
  'leads',
  'students',
  'applications',
  'admissions',
  'campaigns',
  'marketing-automation',
  'communications',
  'call-center',
  'whatsapp',
  'emails',
  'sms',
  'notifications',
  'mobile-app',
  'calendar',
  'tasks',
  'documents',
  'payments',
  'finance',
  'scholarship',
  'interview',
  'events',
  'field-force',
  'reports',
  'dashboard',
  'analytics',
  'ai-features',
  'integrations',
  'security',
  'tenants',
  'settings',
  'learning',
  'automation',
] as const;

export const EDUCATION_PLATFORM_USER_ROLES = [
  'super_admin',
  'organization_admin',
  'branch_admin',
  'admission_manager',
  'admission_counselor',
  'marketing_executive',
  'sales_executive',
  'call-center',
  'finance',
  'field_agent',
  'student',
  'parent',
] as const;
