export const EDUCATION_PLATFORM_MODULE_KEYS = [
  'authentication',
  'user_management',
  'organization_management',
  'lead_management',
  'application_management',
  'admission_management',
  'marketing_automation',
  'communication',
  'call_center',
  'whatsapp',
  'email',
  'sms',
  'mobile',
  'calendar',
  'task_management',
  'document_management',
  'payment',
  'finance',
  'scholarship',
  'interview',
  'event_management',
  'field_force_automation',
  'reports',
  'dashboard',
  'analytics',
  'ai_features',
  'integrations',
  'security',
] as const;

export const EDUCATION_PLATFORM_USER_ROLES = [
  'super_admin',
  'organization_admin',
  'branch_admin',
  'admission_manager',
  'admission_counselor',
  'marketing_executive',
  'sales_executive',
  'call_center',
  'finance',
  'field_agent',
  'student',
  'parent',
] as const;
