export const EDUCATION_PLATFORM_MODULE_KEYS = [
  'platform-foundation',
  'authentication',
  'users',
  'organizations',
  'branches',
  'departments',
  'teams',
  'billing',
  'branding',
  'global-settings',
  'audit-logs',
  'leads',
  'contacts',
  'lead-sources',
  'lead-stages',
  'activities',
  'notes',
  'follow-ups',
  'meetings',
  'assignments',
  'tags',
  'custom-fields',
  'imports-exports',
  'students',
  'academic-sessions',
  'programs',
  'courses',
  'specializations',
  'applications',
  'admissions',
  'enrollment',
  'fees',
  'campaigns',
  'marketing-automation',
  'landing-pages',
  'lead-scoring',
  'marketing-attribution',
  'telephony',
  'chatbots',
  'communications',
  'call-center',
  'whatsapp',
  'emails',
  'sms',
  'notifications',
  'mobile-app',
  'calendar',
  'tasks',
  'documents',
  'payments',
  'finance',
  'scholarship',
  'interview',
  'events',
  'field-force',
  'reports',
  'dashboard',
  'analytics',
  'ai-features',
  'integrations',
  'security',
  'settings',
  'learning',
  'automation',
] as const;

export const EDUCATION_PLATFORM_USER_ROLES = [
  'super_admin',
  'organization_admin',
  'branch_admin',
  'admission_manager',
  'admission_counselor',
  'marketing_executive',
  'sales_executive',
  'call-center',
  'finance',
  'field_agent',
  // Dual-surface org staff: full CRM access plus a mobile-app companion.
  // Distinct from the unrelated, currently-unused `Role.MENTOR` enum value
  // (a pre-existing naming collision between this org-membership vocabulary
  // and the platform `Role` enum, not introduced by this entry).
  'mentor',
  'student',
  'parent',
] as const;
