export enum ErrorCode {
  // =========================
  // AUTH
  // =========================
  AUTH_INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS',
  AUTH_INVALID_PASSWORD = 'AUTH.INVALID_PASSWORD',
  AUTH_USER_NOT_FOUND = 'AUTH.USER_NOT_FOUND',
  AUTH_USER_ALREADY_EXISTS = 'AUTH.USER_ALREADY_EXISTS',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH.EMAIL_ALREADY_EXISTS',
  AUTH_PHONE_ALREADY_EXISTS = 'AUTH.PHONE_ALREADY_EXISTS',
  AUTH_INVALID_TOKEN = 'AUTH.INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH.TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH.REFRESH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH.UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH.FORBIDDEN',
  AUTH_INVALID_OTP = 'AUTH.INVALID_OTP',
  AUTH_OTP_EXPIRED = 'AUTH.OTP_EXPIRED',
  AUTH_OTP_LIMIT_EXCEEDED = 'AUTH.OTP_LIMIT_EXCEEDED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH.EMAIL_NOT_VERIFIED',
  AUTH_PHONE_NOT_VERIFIED = 'AUTH.PHONE_NOT_VERIFIED',
  AUTH_ACCOUNT_BLOCKED = 'AUTH.ACCOUNT_BLOCKED',
  AUTH_ACCOUNT_DISABLED = 'AUTH.ACCOUNT_DISABLED',
  AUTH_ACCOUNT_DELETED = 'AUTH.ACCOUNT_DELETED',
  AUTH_SESSION_EXPIRED = 'AUTH.SESSION_EXPIRED',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH.INVALID_REFRESH_TOKEN',
  AUTH_PASSWORD_MISMATCH = 'AUTH.PASSWORD_MISMATCH',
  AUTH_OLD_PASSWORD_INCORRECT = 'AUTH.OLD_PASSWORD_INCORRECT',

  // =========================
  // USER
  // =========================
  USER_NOT_FOUND = 'USER.NOT_FOUND',
  USER_ALREADY_BLOCKED = 'USER.ALREADY_BLOCKED',
  USER_NOT_BLOCKED = 'USER.NOT_BLOCKED',
  USER_ALREADY_REPORTED = 'USER.ALREADY_REPORTED',
  USER_INACTIVE = 'USER.INACTIVE',

  // =========================
  // PROFILE
  // =========================
  PROFILE_NOT_FOUND = 'PROFILE.NOT_FOUND',
  PROFILE_ALREADY_EXISTS = 'PROFILE.ALREADY_EXISTS',
  PROFILE_INCOMPLETE = 'PROFILE.INCOMPLETE',
  PROFILE_NOT_VERIFIED = 'PROFILE.NOT_VERIFIED',
  PROFILE_ALREADY_VERIFIED = 'PROFILE.ALREADY_VERIFIED',
  PROFILE_IMAGE_LIMIT_EXCEEDED = 'PROFILE.IMAGE_LIMIT_EXCEEDED',
  PROFILE_IMAGE_NOT_FOUND = 'PROFILE.IMAGE_NOT_FOUND',
  PROFILE_IMAGE_REQUIRED = 'PROFILE.IMAGE_REQUIRED',
  PROFILE_APPROVAL_PENDING = 'PROFILE.APPROVAL_PENDING',
  PROFILE_REJECTED = 'PROFILE.REJECTED',

  // =========================
  // PREFERENCES
  // =========================
  PREFERENCES_NOT_FOUND = 'PREFERENCES.NOT_FOUND',
  PREFERENCES_INVALID_RANGE = 'PREFERENCES.INVALID_RANGE',

  // =========================
  // SETTINGS
  // =========================
  SETTINGS_NOT_FOUND = 'SETTINGS.NOT_FOUND',
  SETTINGS_UPDATE_FAILED = 'SETTINGS.UPDATE_FAILED',
  SETTINGS_ACCOUNT_CHANGE_FAILED = 'SETTINGS.ACCOUNT_CHANGE_FAILED',
  SETTINGS_DEVICE_NOT_FOUND = 'SETTINGS.DEVICE_NOT_FOUND',

  // =========================
  // CHAT
  // =========================
  CHAT_NOT_FOUND = 'CHAT.NOT_FOUND',
  CHAT_ACCESS_DENIED = 'CHAT.ACCESS_DENIED',
  CHAT_MESSAGE_NOT_FOUND = 'CHAT.MESSAGE.NOT_FOUND',
  CHAT_MESSAGE_EMPTY = 'CHAT.MESSAGE.EMPTY',
  CHAT_ATTACHMENT_INVALID = 'CHAT.ATTACHMENT.INVALID',

  // =========================
  // SEARCH
  // =========================
  SEARCH_INVALID_FILTER = 'SEARCH.INVALID_FILTER',
  SEARCH_INVALID_SORT = 'SEARCH.INVALID_SORT',

  // =========================
  // SUBSCRIPTION
  // =========================
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION.NOT_FOUND',
  SUBSCRIPTION_ALREADY_ACTIVE = 'SUBSCRIPTION.ALREADY_ACTIVE',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION.EXPIRED',
  SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION.REQUIRED',
  SUBSCRIPTION_FEATURE_NOT_AVAILABLE = 'SUBSCRIPTION.FEATURE_NOT_AVAILABLE',

  // =========================
  // PAYMENT
  // =========================
  PAYMENT_FAILED = 'PAYMENT.FAILED',
  PAYMENT_NOT_FOUND = 'PAYMENT.NOT_FOUND',
  PAYMENT_ALREADY_VERIFIED = 'PAYMENT.ALREADY_VERIFIED',
  PAYMENT_VERIFICATION_FAILED = 'PAYMENT.VERIFICATION_FAILED',
  PAYMENT_REFUND_FAILED = 'PAYMENT.REFUND_FAILED',

  // =========================
  // ADMIN / ANALYTICS
  // =========================
  ADMIN_OPERATION_FAILED = 'ADMIN.OPERATION_FAILED',
  ANALYTICS_OPERATION_FAILED = 'ANALYTICS.OPERATION_FAILED',

  // =========================
  // FILES
  // =========================
  FILE_NOT_FOUND = 'FILE.NOT_FOUND',
  FILE_UPLOAD_FAILED = 'FILE.UPLOAD_FAILED',
  FILE_TOO_LARGE = 'FILE.TOO_LARGE',
  FILE_INVALID_TYPE = 'FILE.INVALID_TYPE',

  // =========================
  // NOTIFICATION
  // =========================
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION.NOT_FOUND',

  // =========================
  // VALIDATION
  // =========================
  VALIDATION_FAILED = 'COMMON.VALIDATION_FAILED',
  INVALID_REQUEST = 'COMMON.INVALID_REQUEST',
  INVALID_INPUT = 'COMMON.INVALID_INPUT',
  INVALID_ID = 'COMMON.INVALID_ID',
  INVALID_DATE = 'COMMON.INVALID_DATE',
  INVALID_ENUM_VALUE = 'COMMON.INVALID_ENUM_VALUE',
  REQUIRED_FIELD_MISSING = 'COMMON.REQUIRED_FIELD_MISSING',

  // =========================
  // RATE LIMIT
  // =========================
  TOO_MANY_REQUESTS = 'COMMON.TOO_MANY_REQUESTS',

  // =========================
  // ACCESS
  // =========================
  ACCESS_DENIED = 'COMMON.ACCESS_DENIED',

  // =========================
  // SERVER
  // =========================
  INTERNAL_ERROR = 'COMMON.INTERNAL_ERROR',
  DATABASE_ERROR = 'COMMON.DATABASE_ERROR',
  SERVICE_UNAVAILABLE = 'COMMON.SERVICE_UNAVAILABLE',
  ENDPOINT_NOT_FOUND = 'COMMON.ENDPOINT_NOT_FOUND',
  METHOD_NOT_ALLOWED = 'COMMON.METHOD_NOT_ALLOWED',
  REQUEST_TIMEOUT = 'COMMON.REQUEST_TIMEOUT',

  // =========================
  // THIRD PARTY
  // =========================
  THIRD_PARTY_ERROR = 'THIRD_PARTY.ERROR',
  SMS_SERVICE_FAILED = 'THIRD_PARTY.SMS_SERVICE_FAILED',
  EMAIL_SERVICE_FAILED = 'THIRD_PARTY.EMAIL_SERVICE_FAILED',
  STORAGE_SERVICE_FAILED = 'THIRD_PARTY.STORAGE_SERVICE_FAILED',
  PAYMENT_GATEWAY_ERROR = 'THIRD_PARTY.PAYMENT_GATEWAY_ERROR',

  // =========================
  // REFERRALS
  // =========================
  REFERRAL_CODE_INVALID = 'REFERRAL.CODE_INVALID',
  REFERRAL_SELF_NOT_ALLOWED = 'REFERRAL.SELF_NOT_ALLOWED',
  REFERRAL_ALREADY_APPLIED = 'REFERRAL.ALREADY_APPLIED',
}
