import { Theme } from '@/core/theme/types';
import { StyleSheet } from 'react-native';

export const onboardingStyles = (theme: Theme) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.colors.white },
    container: { flex: 1 },
    content: {
      flexGrow: 1,
      paddingVertical: 24,
      paddingHorizontal: 20,
    },
    progressBarWrapper: {
      height: 4,
      backgroundColor: theme.colors.border,
    },
    progressFill: {
      height: 4,
      backgroundColor: theme.colors.primary,
    },
    stepIndicatorContainer: {
      backgroundColor: theme.colors.white,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    stepIndicatorContent: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
    },
    stepIndicatorItem: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    stepDot: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.colors.backgroundLight,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    stepDotActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    stepDotCompleted: {
      backgroundColor: theme.colors.success,
      borderColor: theme.colors.success,
    },
    stepDotLabel: {
      fontSize: 10,
      color: theme.colors.textMuted,
      marginLeft: 4,
      marginRight: 2,
    },
    stepDotLabelActive: {
      color: theme.colors.primary,
      fontWeight: '700',
    },
    stepDotLabelCompleted: {
      color: theme.colors.success,
    },
    stepConnector: {
      width: 20,
      height: 2,
      backgroundColor: theme.colors.border,
      marginHorizontal: 4,
    },
    stepConnectorCompleted: {
      backgroundColor: theme.colors.success,
    },
    stepTitle: {
      fontSize: 22,
      fontWeight: '700',
      marginBottom: 6,
      color: theme.colors.textPrimary,
    },
    subtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      marginBottom: 20,
      lineHeight: 20,
    },
    label: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
      marginBottom: 6,
    },
    input: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 13,
      marginBottom: 12,
      fontSize: 15,
      color: theme.colors.textPrimary,
      backgroundColor: theme.colors.inputBackground,
    },
    textArea: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 13,
      marginBottom: 12,
      fontSize: 15,
      color: theme.colors.textPrimary,
      backgroundColor: theme.colors.inputBackground,
      height: 100,
    },
    inputError: {
      borderColor: theme.colors.error,
      backgroundColor: theme.colors.errorLight,
    },
    dropdownTrigger: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    dropdownValueText: {
      color: theme.colors.textPrimary,
      fontSize: 15,
    },
    dropdownPlaceholder: {
      color: theme.colors.textMuted,
      fontSize: 15,
    },
    dropdown: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 10,
      marginBottom: 12,
      backgroundColor: theme.colors.white,
      maxHeight: 220,
      boxShadow: `0px 2px 6px rgba(0, 0, 0, 0.08)`,
      elevation: 4,
    },
    dropdownItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 13,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    dropdownItemActive: {
      backgroundColor: theme.colors.primaryLight,
    },
    dropdownItemText: {
      fontSize: 15,
      color: theme.colors.textPrimary,
    },
    dropdownItemTextActive: {
      color: theme.colors.primary,
      fontWeight: '600',
    },
    chipRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 12,
    },
    chip: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      backgroundColor: theme.colors.inputBackground,
    },
    chipActive: {
      backgroundColor: theme.colors.primaryLight,
      borderColor: theme.colors.primary,
    },
    chipText: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      fontWeight: '500',
    },
    chipTextActive: {
      color: theme.colors.primary,
      fontWeight: '700',
    },
    row: {
      flexDirection: 'row',
      gap: 12,
    },
    halfField: {
      flex: 1,
    },
    error: {
      color: theme.colors.error,
      marginBottom: 10,
      marginTop: -6,
      fontSize: 12,
    },
    buttonContainer: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 24,
      marginBottom: 20,
      paddingBottom: 20,
    },
    primaryButton: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: theme.colors.primary,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    primaryButtonText: {
      color: theme.colors.white,
      fontWeight: '700',
      fontSize: 16,
    },
    secondaryButton: {
      flex: 1,
      flexDirection: 'row',
      borderWidth: 1,
      borderColor: theme.colors.primary,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    secondaryButtonText: {
      color: theme.colors.primary,
      fontWeight: '600',
      fontSize: 16,
    },
    disabledButton: {
      opacity: 0.6,
    },
    reviewCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      boxShadow: `0px 1px 4px rgba(0, 0, 0, 0.04)`,
      elevation: 1,
    },
    reviewSectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginBottom: 10,
    },
    reviewSection: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    reviewLabel: {
      fontSize: 13,
      color: theme.colors.textMuted,
      flex: 1,
    },
    reviewValue: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      flex: 2,
      textAlign: 'right',
    },

    ///////////////////////////
    // ─── Photo styles (add to onboardingStyles StyleSheet.create block) ───────────

    photoRow: {
      flexDirection: 'row',
      gap: 12,
      paddingVertical: 8,
      paddingHorizontal: 2,
    },
    photoWrapper: {
      width: 110,
      height: 140,
      borderRadius: 12,
      overflow: 'hidden',
      position: 'relative',
    },
    photo: {
      width: '100%',
      height: '100%',
      borderRadius: 12,
    },
    primaryBadge: {
      position: 'absolute',
      top: 6,
      left: 6,
      backgroundColor: theme.colors.primary,
      borderRadius: 6,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    primaryBadgeText: {
      color: theme.colors.white,
      fontSize: 10,
      fontWeight: '700',
    },
    photoActions: {
      position: 'absolute',
      bottom: 6,
      right: 6,
      flexDirection: 'row',
      gap: 6,
    },
    photoActionBtn: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 2,
    },
    photoActionBtnDanger: {
      backgroundColor: theme.colors.errorLight,
    },
    addPhotoBtn: {
      width: 110,
      height: 140,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: theme.colors.border,
      borderStyle: 'dashed',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: theme.colors.backgroundLight,
    },
    addPhotoText: {
      fontSize: 12,
      color: theme.colors.textMuted,
      fontWeight: '500',
    },
    photoHint: {
      fontSize: 12,
      color: theme.colors.textMuted,
      marginTop: 10,
      marginBottom: 4,
      lineHeight: 18,
    },
    photoEmptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 32,
      gap: 8,
    },
    photoEmptyTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    photoEmptySubtitle: {
      fontSize: 13,
      color: theme.colors.textMuted,
      textAlign: 'center',
    },
  });
