import {
  Countries,
  Genders,
  Qualifications,
  Religions,
  PersonalityBadges,
} from '@/core/types';
import { ProfileData } from './EditProfile.types';

export const INITIAL_PROFILE: ProfileData = {
  personal: {
    firstName: '',
    lastName: '',
    gender: Genders.MALE,
    dateOfBirth: '',
    hobbies: [],
    personalityBadges: [
      PersonalityBadges.CURIOUS_LEARNER,
      PersonalityBadges.GOAL_ORIENTED,
      PersonalityBadges.CONSISTENT_PRACTICE,
    ],
    languages: [],
    aboutMe: '',
    religion: Religions.HINDU,
    religiousDetails: {},
    country: Countries.INDIA,
    state: '',
    city: '',
    citizenship: '',
    isNri: false,
    residencyCountry: Countries.INDIA,
    visaStatus: '',
    abroadSince: '',
    motherTongue: '',
  },
  physical: {
    accessibilityNeeds: [],
  },
  education: {
    qualification: Qualifications.BA,
    field: '',
    university: '',
    occupation: '',
    previousEducationSummary: '',
    examScoreSummary: '',
    coursePreference: '',
    preferredSubjects: [],
  },
  family: {
    fatherName: '',
    motherName: '',
    fatherOccupation: '',
    motherOccupation: '',
    guardianName: '',
    guardianRelation: '',
    primaryGuardianPhone: '',
    primaryGuardianEmail: '',
  },
  images: [],
};
