export enum Diet {
  VEGETARIAN = 'VEGETARIAN',
  NON_VEGETARIAN = 'NON_VEGETARIAN',
  EGGETARIAN = 'EGGETARIAN',
  VEGAN = 'VEGAN',
  JAIN = 'JAIN',
  SATVIK = 'SATVIK',
  HALAL = 'HALAL',
  KOSHER = 'KOSHER',
  OPEN_TO = 'OPEN_TO',
}