import type { DemoUser } from "../store";
import type { AdminModule, IconName, ModuleStatus } from "./adminTypes";

export type ThemeMode = "light" | "dark";
export type OrganizationSetupKind =
  "branch" | "department" | "team" | "branding" | "channel";

export const dedicatedAdminModuleIds = new Set([
  "admissions",
  "applications",
  "assignments",
  "automation",
  "call-center",
  "campaigns",
  "communications",
  "documents",
  "emails",
  "events",
  "field-force",
  "finance",
  "interview",
  "leads",
  "lead-sources",
  "lead-stages",
  "reports",
  "scholarship",
  "support",
  "sms",
  "tasks",
  "whatsapp",
]);

export const organizationStructureModuleIds = new Set([
  "branches",
  "departments",
  "teams",
]);

export const readonlyFormColumns = new Set([
  "assigned",
  "assigned to",
  "branches",
  "count",
  "created",
  "created at",
  "id",
  "last active",
  "last active at",
  "last login",
  "lastlogin",
  "members",
  "modules",
  "owner",
  "permissions",
  "records",
  "role",
  "roles",
  "status",
  "organization",
  "organization id",
  "updated",
  "updated at",
]);

export function getEditableModuleColumns(module: AdminModule) {
  if (module.id === "roles") return ["Description", "Permissions"];
  if (module.id === "permissions") return ["Module", "Description"];
  if (module.id === "leads") {
    return [
      "First Name",
      "Middle Name",
      "Last Name",
      "Email",
      "Phone",
      "Alternate Phone",
      "Date Of Birth",
      "Gender",
      "Preferred Language",
      "Country",
      "State",
      "City",
      "Postal Code",
      "Full Address",
      "Academic Level",
      "Interested Program",
      "Course",
      "Specialization",
      "Academic Session",
      "Preferred Campus",
      "Preferred Mode",
      "Intake",
      "Lead Source",
      "Sub Source",
      "Campaign",
      "Referral",
      "Partner",
      "UTM Source",
      "UTM Medium",
      "UTM Campaign",
      "UTM Term",
      "UTM Content",
      "Landing Page",
      "Form Source",
      "Branch",
      "Department",
      "Team",
      "Assigned Counselor",
      "Assignment Method",
      "Current Qualification",
      "Percentage/CGPA",
      "Graduation Year",
      "Entrance Exam",
      "Exam Score",
      "Work Experience",
      "Budget Range",
      "Preferred Location",
      "Stage",
      "Priority",
      "Temperature",
      "Lead Score",
      "Lost Reason",
      "Disqualification Reason",
      "Next Follow-up Date",
      "Follow-up Type",
      "Follow-up Note",
      "Tags",
      "Notes",
      "Consent Status",
    ];
  }
  if (module.id === "lead-sources") {
    return [
      "Name",
      "Code",
      "Category",
      "Parent Source",
      "Description",
      "Default Assignment Rule",
      "Default Campaign",
      "Cost",
      "Active Status",
    ];
  }
  if (module.id === "lead-stages") {
    return [
      "Name",
      "Code",
      "Display Order",
      "Color",
      "Category",
      "Is Initial Stage",
      "Is Converted Stage",
      "Is Lost Stage",
      "Requires Remarks",
      "Mandatory Fields Before Entry",
      "Allowed Next Stages",
      "SLA Duration",
      "Escalation Rule",
      "Status",
    ];
  }
  if (module.id === "campaigns") {
    return [
      "Channel",
      "Audience",
      "Leads",
      "Applications",
      "Spend",
      "Roi",
      "Utm Source",
      "Utm Medium",
      "Utm Campaign",
      "Utm Term",
      "Utm Content",
      "Drip Steps",
    ];
  }
  if (
    module.id === "communications" ||
    module.id === "emails" ||
    module.id === "sms"
  ) {
    return ["Channel", "Direction", "Entity Type", "Entity Id", "Content"];
  }
  if (module.id === "tasks") {
    return [
      "Entity Type",
      "Entity Id",
      "Assigned To",
      "Reminder At",
      "Recurring Rule",
    ];
  }
  if (module.id === "documents") {
    return ["Entity Type", "Entity Id", "Category", "Url", "Mime Type", "Size"];
  }
  if (module.id === "reports") {
    return ["Module Key", "Report Type", "Columns", "Filters", "Schedule"];
  }
  if (module.id === "automation") {
    return [
      "Module Key",
      "Trigger",
      "Conditions",
      "Actions",
      "Priority",
      "Retry Policy",
      "Sla Policy",
    ];
  }
  return module.columns.slice(1, 6).filter((column) => {
    const normalized = column.trim().toLowerCase().replaceAll("_", " ");
    return (
      !readonlyFormColumns.has(normalized) &&
      !normalized.endsWith(" id") &&
      !normalized.includes("last login") &&
      !normalized.includes("created") &&
      !normalized.includes("updated")
    );
  });
}

export const moduleIcons: Record<string, IconName> = {
  admissions: "check",
  "academic-sessions": "calendar",
  "ai-features": "ai",
  analytics: "analytics",
  applications: "document",
  assignments: "task",
  "audit-logs": "shield",
  authentication: "lock",
  automation: "automation",
  billing: "payment",
  branding: "organization",
  branches: "building",
  calendar: "calendar",
  "call-center": "headset",
  campaigns: "campaign",
  chatbots: "ai",
  communications: "chat",
  contacts: "user",
  courses: "graduation",
  "custom-fields": "settings",
  dashboard: "dashboard",
  departments: "organization",
  documents: "document",
  emails: "mail",
  enrollment: "check",
  fees: "finance",
  "follow-ups": "calendar",
  "global-settings": "settings",
  "imports-exports": "report",
  "landing-pages": "dashboard",
  "lead-scoring": "analytics",
  "lead-sources": "lead",
  "lead-stages": "lead",
  notifications: "chat",
  permissions: "shield",
  events: "calendar",
  "field-force": "mobile",
  finance: "finance",
  integrations: "integration",
  interview: "user",
  leads: "lead",
  learning: "graduation",
  "marketing-attribution": "analytics",
  meetings: "calendar",
  "mobile-app": "mobile",
  notes: "document",
  organizations: "building",
  payments: "payment",
  "platform-foundation": "organization",
  programs: "graduation",
  reports: "report",
  roles: "user",
  scholarship: "graduation",
  security: "shield",
  settings: "settings",
  sms: "chat",
  specializations: "graduation",
  support: "chat",
  students: "user",
  tasks: "task",
  teams: "user",
  telephony: "headset",
  users: "user",
  whatsapp: "chat",
};

export const moduleActions: Record<string, string[]> = {
  admissions: [
    "Collect Fee",
    "Allocate Batch",
    "Provision Plan",
    "Queue Handoff",
    "Complete",
  ],
  applications: [
    "Review",
    "Request Docs",
    "Move Stage",
    "Schedule Interview",
    "Issue Offer",
    "Confirm Admission",
  ],
  authentication: [
    "Review Sessions",
    "Device Console",
    "Update Policy",
    "Configure SSO",
    "Audit Export",
  ],
  campaigns: [
    "Inventory",
    "UTM Setup",
    "Landing Page",
    "Lead Ads",
    "Remarketing",
    "Drip Journey",
    "ROI Report",
    "Conversion Tags",
  ],
  communications: [
    "Send Message",
    "Schedule",
    "Open Inbox",
    "Template",
    "Delivery Status",
    "Opt-in Controls",
  ],
  documents: ["Load Documents", "Request Document", "Verify"],
  "mobile-app": [
    "Counselor Dashboard",
    "Lead Update",
    "Voice Note",
    "Geo Check-in",
    "Offline Sync",
    "Mobile Report",
  ],
  calendar: [
    "Counseling Calendar",
    "Interview Slot",
    "Event Calendar",
    "Reminder",
    "Recurring Schedule",
    "Calendar Sync",
  ],
  finance: [
    "Invoice",
    "Receipt",
    "Refund Approval",
    "Tax Ledger",
    "Collections",
    "Pending Payments",
    "Finance Report",
    "Reconcile",
    "Export Ledger",
  ],
  automation: [
    "Assignment Rule",
    "Reminder Rule",
    "Drip Rule",
    "Escalation Rule",
    "Score Update",
    "Recycle Stale Leads",
    "Webhook",
    "Run Workflow",
    "Execution Log",
  ],
  leads: [
    "Create Lead",
    "Assign",
    "Transfer",
    "Change Stage",
    "Add Note",
    "Schedule Follow-up",
    "Add Task",
    "Call",
    "Email",
    "SMS",
    "WhatsApp",
    "Start Application",
    "Mark Lost",
    "Merge Duplicate",
    "Convert Contact",
    "Add Document",
    "Check Duplicates",
    "Import Leads",
    "Export Leads",
    "Score Lead",
    "Update Tags",
    "Add Attachment",
  ],
  integrations: [
    "Check Providers",
    "Configure Provider",
    "Webhook",
    "Callback Verify",
    "Health Check",
    "Export Report",
  ],
  "call-center": [
    "Incoming Call",
    "Outgoing Call",
    "Dialer Queue",
    "Recording Ref",
    "Disposition",
    "Follow-up",
    "Call Analytics",
  ],
  organizations: [
    "Create Organization",
    "Create Branch",
    "Create Department",
    "Create Team",
    "Update Branding",
    "Configure Channel",
    "Export Setup",
  ],
  branches: ["Create Branch", "Export Setup", "Audit"],
  departments: ["Create Department", "Export Setup", "Audit"],
  teams: ["Create Team", "Export Setup", "Audit"],
  reports: [
    "Create Report",
    "Saved Report",
    "Dashboard Report",
    "Schedule Report",
    "Export Report",
    "Role Report",
  ],
  security: [
    "Load Policy",
    "Update Policy",
    "Configure MFA",
    "Configure SSO",
    "Audit Export",
    "Schedule Report",
  ],
  scholarship: [
    "Evaluate",
    "Verify",
    "Decision",
    "Award Amount",
    "Payment Impact",
    "Audit Trail",
    "Complete",
  ],
  interview: [
    "Schedule",
    "Assign Panel",
    "Record Result",
    "Score",
    "Recommend Offer",
    "Handoff",
    "Complete",
  ],
  whatsapp: [
    "Template",
    "Media",
    "Buttons",
    "Flows",
    "Bulk Send",
    "Automation",
    "Delivery Report",
    "Conversation History",
  ],
  emails: [
    "Template",
    "Bulk Mail",
    "Drip Campaign",
    "Open Tracking",
    "Click Tracking",
    "Bounces",
    "Unsubscribe",
    "Approval",
  ],
  sms: [
    "OTP",
    "Transactional",
    "Promotional",
    "Bulk SMS",
    "Template",
    "Provider Callback",
    "Delivery Report",
    "Compliance Status",
  ],
  notifications: [
    "Open Inbox",
    "Templates",
    "Delivery Logs",
    "Analytics",
    "Failed Queue",
    "Replay",
    "Preferences",
    "Provider Check",
  ],
  tasks: [
    "Create Task",
    "Board View",
    "SLA",
    "Reminder",
    "Comment",
    "Escalate",
    "Reassign",
    "Complete",
  ],
  payments: [
    "Application Fee",
    "Admission Fee",
    "Installment",
    "Payment Link",
    "Receipt",
    "Refund",
    "Reconciliation",
  ],
  events: [
    "Registration Form",
    "Attendance",
    "QR Check-in",
    "Webinar",
    "Branch Visit",
    "Event Lead Capture",
    "Complete",
  ],
  "field-force": [
    "Geo Tracking",
    "Route Plan",
    "Attendance",
    "Mileage",
    "Check-in",
    "Check-out",
    "Visit History",
    "Complete",
  ],
  dashboard: [
    "CEO Dashboard",
    "Management Dashboard",
    "Marketing Dashboard",
    "Finance Dashboard",
    "Counselor Dashboard",
    "Refresh KPIs",
  ],
  analytics: [
    "Lead Funnel",
    "Admission Funnel",
    "Revenue Analytics",
    "ROI Analytics",
    "Counselor Productivity",
    "Forecasting",
  ],
  "ai-features": [
    "Lead Scoring",
    "Prediction",
    "Chatbot",
    "Conversation Summary",
    "Auto Reply",
    "Follow-up Suggestion",
  ],
  users: ["Create User"],
  roles: ["Create Role"],
  permissions: ["Create Permission"],
};

export const securityControlGroups = [
  {
    icon: "user" as IconName,
    title: "RBAC & Access",
    metric: "42 roles",
    description:
      "Roles, permissions, teams, departments, and organization memberships.",
    actions: ["Manage RBAC", "Review Access", "Export Users"],
  },
  {
    icon: "report" as IconName,
    title: "Audit & Activity",
    metric: "18.4k events",
    description:
      "Audit logs, admin activity, session history, and sensitive changes.",
    actions: ["Audit Export", "Activity Logs"],
  },
  {
    icon: "shield" as IconName,
    title: "Network Controls",
    metric: "6 rules",
    description:
      "IP restrictions, VPN allowlists, device/session rules, and geo policy.",
    actions: ["Load Policy", "Update Policy"],
  },
  {
    icon: "lock" as IconName,
    title: "Data Protection",
    metric: "9 policies",
    description:
      "Data masking, encryption policy, backups, retention, and admin exports.",
    actions: ["Update Policy", "Audit Export"],
  },
  {
    icon: "integration" as IconName,
    title: "Identity Providers",
    metric: "2 providers",
    description:
      "2FA, SSO, Microsoft/Google login, password policy, and recovery rules.",
    actions: ["Update Policy", "Configure Provider"],
  },
  {
    icon: "settings" as IconName,
    title: "Compliance Ops",
    metric: "12 checks",
    description:
      "Scheduled exports, backup verification, legal hold, and compliance review.",
    actions: ["Audit Export", "Schedule Report"],
  },
];

export const defaultCrmUsers = [
  {
    email: "super.admin@mentora.test",
    name: "Super Admin",
    contexts: [
      {
        organization: "All Organizations",
        branch: "All Branches",
        role: "super_admin",
        label: "Platform Super Admin",
        modules: [
          "dashboard",
          "organizations",
          "security",
          "analytics",
          "integrations",
        ],
      },
    ],
  },
  {
    email: "counselor@mentora.test",
    name: "Admission Counselor",
    contexts: [
      {
        organization: "Webnza Coaching",
        branch: "Delhi",
        role: "admission_counselor",
        label: "Counselor Workspace",
        modules: [
          "leads",
          "applications",
          "tasks",
          "communications",
          "calendar",
        ],
      },
    ],
  },
  {
    email: "finance@mentora.test",
    name: "Finance Manager",
    contexts: [
      {
        organization: "Webnza Coaching",
        branch: "All Branches",
        role: "finance",
        label: "Finance Workspace",
        modules: ["payments", "finance", "reports", "scholarship"],
      },
    ],
  },
] satisfies DemoUser[];

export const navGroups = [
  {
    title: "Platform Foundation",
    items: [
      "dashboard",
      "platform-foundation",
      "billing",
      "payments",
      "branding",
      "global-settings",
      "audit-logs",
    ],
  },
  {
    title: "Identity & Organization",
    items: [
      "authentication",
      "users",
      "roles",
      "permissions",
      "organizations",
      "branches",
      "departments",
      "teams",
      "security",
    ],
  },
  {
    title: "Generic CRM",
    items: [
      "leads",
      "contacts",
      "lead-sources",
      "lead-stages",
      "activities",
      "notes",
      "tasks",
      "follow-ups",
      "meetings",
      "assignments",
      "tags",
      "custom-fields",
      "imports-exports",
      "communications",
    ],
  },
  {
    title: "Education",
    items: [
      "students",
      "academic-sessions",
      "programs",
      "courses",
      "specializations",
      "applications",
      "admissions",
      "interview",
      "scholarship",
      "enrollment",
      "fees",
      "documents",
      "learning",
    ],
  },
  {
    title: "Growth & Automation",
    items: [
      "campaigns",
      "marketing-automation",
      "landing-pages",
      "emails",
      "sms",
      "whatsapp",
      "telephony",
      "call-center",
      "chatbots",
      "lead-scoring",
      "marketing-attribution",
      "notifications",
      "automation",
      "analytics",
      "ai-features",
    ],
  },
  {
    title: "Operations",
    items: [
      "mobile-app",
      "calendar",
      "events",
      "field-force",
      "support",
      "finance",
      "reports",
      "integrations",
      "settings",
    ],
  },
];

export const modules: AdminModule[] = [
  {
    id: "leads",
    title: "Leads",
    group: "CRM",
    metric: "428",
    description:
      "Capture, deduplicate, score, assign, nurture, and track every enquiry from website, ads, WhatsApp, walk-ins, imports, and APIs.",
    filters: ["Source", "Stage", "Counselor", "Priority"],
    columns: [
      "Lead Number",
      "Applicant Name",
      "Phone",
      "Email",
      "Interested Course",
      "Campus",
      "Lead Stage",
      "Lead Status",
      "Source",
      "Campaign",
      "Assigned Counselor",
      "Team",
      "Lead Score",
      "Priority",
      "Last Contacted",
      "Next Follow-up",
      "Created Date",
      "Age Of Lead",
      "Duplicate Indicator",
    ],
    rows: [
      [
        "Aarav Sharma",
        "JEE Foundation",
        "Website",
        "Contacted",
        "Ritika",
        "Today 4:30 PM",
      ],
      [
        "Meera Iyer",
        "NEET Target",
        "WhatsApp",
        "Application",
        "Sahil",
        "Tomorrow",
      ],
      [
        "Kabir Khan",
        "Class 9 Science",
        "Google Ads",
        "New",
        "Unassigned",
        "Today",
      ],
      ["Rhea Jain", "Class 10 Maths", "Referral", "Counseled", "Dev", "01 Aug"],
      ["Vihaan Rao", "NEET 2026", "Walk-in", "Offer", "Ananya", "03 Aug"],
    ],
  },
  {
    id: "applications",
    title: "Applications",
    group: "CRM",
    metric: "173",
    description:
      "Manage student application forms, documents, reviewer notes, stage movement, interviews, offers, and admission confirmation.",
    filters: ["Course", "Status", "Reviewer", "Completeness"],
    columns: [
      "Application",
      "Student",
      "Course",
      "Status",
      "Completeness",
      "Reviewer",
    ],
    rows: [
      [
        "APP-000143",
        "Meera Iyer",
        "NEET Target",
        "Under review",
        "86%",
        "Ananya",
      ],
      ["APP-000144", "Pranav S", "UPSC Foundation", "Documents", "72%", "Dev"],
      [
        "APP-000145",
        "Rhea Jain",
        "Class 10 Maths",
        "Submitted",
        "94%",
        "Sahil",
      ],
      [
        "APP-000146",
        "Vihaan Rao",
        "NEET 2026",
        "Offer issued",
        "100%",
        "Ritika",
      ],
    ],
  },
  {
    id: "admissions",
    title: "Admissions",
    group: "CRM",
    metric: "64",
    description:
      "Run offer-to-enrollment workflows with fee collection, batch allocation, onboarding, and learning-plan provisioning.",
    filters: ["Offer", "Fee", "Batch", "Owner"],
    columns: ["Student", "Offer", "Fee", "Batch", "Start Date", "Owner"],
    rows: [
      ["Rhea Jain", "Issued", "Pending", "X-CBSE-A1", "01 Aug", "Ritika"],
      ["Vihaan Rao", "Accepted", "Paid", "NEET-26", "03 Aug", "Dev"],
      ["Sara Ali", "Negotiation", "Scholarship", "JEE-27", "05 Aug", "Sahil"],
    ],
  },
  {
    id: "campaigns",
    title: "Campaigns",
    group: "Growth",
    metric: "24",
    description:
      "Track campaign inventory, UTMs, landing pages, lead ads, remarketing audiences, drip journeys, source ROI, and conversion tags.",
    filters: ["Channel", "Campaign", "Source", "ROI"],
    columns: ["Campaign", "Channel", "Leads", "Applications", "Spend", "ROI"],
    rows: [
      ["NEET 2027 Webinar", "Meta", "142", "38", "INR 42K", "3.8x"],
      ["JEE Doubt Solver", "Google", "96", "21", "INR 31K", "2.9x"],
      ["Parent WhatsApp Series", "WhatsApp", "74", "18", "INR 8K", "5.2x"],
    ],
  },
  {
    id: "communications",
    title: "Communications",
    group: "Growth",
    metric: "8,412",
    description:
      "Central email, SMS, WhatsApp, call, push, and in-app message history with templates, delivery status, and opt-in controls.",
    filters: ["Channel", "Template", "Status", "Direction"],
    columns: ["Message", "Channel", "Entity", "Status", "Owner", "Time"],
    rows: [
      [
        "Demo confirmation",
        "WhatsApp",
        "Aarav Sharma",
        "Delivered",
        "System",
        "10:32 AM",
      ],
      [
        "Application reminder",
        "Email",
        "Meera Iyer",
        "Opened",
        "System",
        "09:20 AM",
      ],
      [
        "Parent callback",
        "Call",
        "Rhea Jain",
        "Completed",
        "Sahil",
        "Yesterday",
      ],
    ],
  },
  {
    id: "automation",
    title: "Automation",
    group: "Growth",
    metric: "18",
    description:
      "No-code rules for assignment, reminders, drip communication, escalations, score updates, stale-lead recycling, and webhooks.",
    filters: ["Trigger", "Status", "Owner", "Entity"],
    columns: ["Workflow", "Trigger", "Actions", "Last Run", "Status", "Owner"],
    rows: [
      [
        "Hot lead round-robin",
        "Lead created",
        "Assign + notify",
        "11:15 AM",
        "Active",
        "Ops",
      ],
      [
        "Application nudge",
        "Stage idle",
        "WhatsApp + task",
        "09:00 AM",
        "Active",
        "Marketing",
      ],
      [
        "Fee escalation",
        "Payment overdue",
        "Manager alert",
        "Yesterday",
        "Draft",
        "Finance",
      ],
    ],
  },
  {
    id: "payments",
    title: "Payments",
    group: "Business",
    metric: "INR 18.4L",
    description:
      "Application fees, admission fees, course payments, installments, receipts, refunds, scholarships, waivers, and reconciliation.",
    filters: ["Student", "Purpose", "Status", "Gateway"],
    columns: ["Receipt", "Student", "Purpose", "Amount", "Status", "Gateway"],
    rows: [
      [
        "RCPT-2191",
        "Vihaan Rao",
        "Admission fee",
        "INR 45,000",
        "Paid",
        "Razorpay",
      ],
      [
        "RCPT-2192",
        "Meera Iyer",
        "Application fee",
        "INR 1,000",
        "Paid",
        "Razorpay",
      ],
      [
        "RCPT-2193",
        "Rhea Jain",
        "Course installment",
        "INR 12,500",
        "Pending",
        "Link",
      ],
    ],
  },
  {
    id: "reports",
    title: "Reports",
    group: "Growth",
    metric: "37",
    description:
      "Funnel, source ROI, counselor productivity, branch performance, payment collections, SLA, admissions forecast, and learning reports.",
    filters: ["Report", "Owner", "Refresh", "Status"],
    columns: ["Report", "Owner", "Refresh", "Rows", "Exports", "Status"],
    rows: [
      [
        "Admission funnel",
        "Management",
        "Hourly",
        "12,842",
        "CSV/PDF",
        "Ready",
      ],
      ["Counselor productivity", "Sales", "Daily", "4,320", "CSV", "Ready"],
      ["Campaign ROI", "Marketing", "Hourly", "2,148", "CSV/PDF", "Ready"],
    ],
  },
  {
    id: "notifications",
    title: "Notifications",
    group: "Growth",
    metric: "3 alerts",
    description:
      "Central notification inbox, templates, delivery logs, failed queue, analytics, preferences, and provider health.",
    filters: ["Type", "Channel", "Status", "Owner"],
    columns: [
      "Notification",
      "Channel",
      "Audience",
      "Status",
      "Owner",
      "Updated",
    ],
    rows: [
      ["Unread parent digest", "In-app", "Parents", "Pending", "Ops", "Today"],
      ["Failed SMS batch", "SMS", "Students", "Review", "Support", "Today"],
      [
        "Template approval",
        "Email",
        "Leads",
        "Active",
        "Marketing",
        "Yesterday",
      ],
    ],
  },
  {
    id: "support",
    title: "Support",
    group: "Operations",
    metric: "0 open",
    description:
      "Support tickets, learner and parent issues, SLA queues, agent replies, priority handling, resolution tracking, and closure audits.",
    filters: ["Status", "Priority", "Category", "Agent"],
    columns: ["Ticket", "Category", "Priority", "Status", "Replies", "Updated"],
    rows: [],
  },
  {
    id: "learning",
    title: "Learning Operations",
    group: "Business",
    metric: "1,284",
    description:
      "Bridge enrolled students into Mentora learning: profiles, plans, AI tutor sessions, online classes, tests, progress, and parent summaries.",
    filters: ["Student", "Plan", "Tutor", "Progress"],
    columns: [
      "Student",
      "Plan",
      "Next Class",
      "Tutor",
      "Progress",
      "Parent Alert",
    ],
    rows: [
      [
        "Aarav Sharma",
        "JEE Foundation",
        "Today 6:00 PM",
        "AI Tutor",
        "62%",
        "Weekly",
      ],
      [
        "Meera Iyer",
        "NEET Target",
        "Tomorrow 7:00 PM",
        "Online Tutor",
        "48%",
        "After tests",
      ],
      [
        "Rhea Jain",
        "Class 10 Maths",
        "Fri 5:00 PM",
        "AI Tutor",
        "74%",
        "Immediate",
      ],
    ],
  },
  {
    id: "settings",
    title: "Settings",
    group: "Business",
    metric: "42",
    description:
      "Configure lead stages, sources, forms, fields, templates, roles, permissions, consent, child-safety policies, integrations, and webhooks.",
    filters: ["Category", "Owner", "Status", "Scope"],
    columns: ["Setting", "Category", "Scope", "Updated", "Owner", "Status"],
    rows: [
      ["Lead stages", "CRM", "Organization", "Today", "Ops", "Active"],
      [
        "WhatsApp templates",
        "Communication",
        "Organization",
        "Yesterday",
        "Marketing",
        "Review",
      ],
      [
        "Student consent policy",
        "Safety",
        "Platform",
        "22 Jul",
        "Legal",
        "Active",
      ],
    ],
  },
];

export function createLayerModule(
  id: string,
  title: string,
  group: string,
  description: string,
  columns: string[] = ["Record", "Type", "Owner", "Status", "Updated", "Scope"],
): AdminModule {
  return {
    id,
    title,
    group,
    metric: "Ready",
    description,
    filters: ["Type", "Owner", "Status", "Scope"],
    columns,
    rows: [],
  };
}

export const extraModules: AdminModule[] = [
  {
    id: "my-profile",
    title: "My Profile",
    group: "Account",
    metric: "Account",
    description: "Current CRM user identity, role, context, and access scope.",
    filters: [],
    columns: ["Field", "Value"],
    rows: [],
  },
  {
    id: "change-password",
    title: "Change Password",
    group: "Account",
    metric: "Security",
    description: "Update the current CRM account password.",
    filters: [],
    columns: ["Control", "Status"],
    rows: [],
  },
  createLayerModule(
    "platform-foundation",
    "Platform Foundation",
    "Platform Foundation",
    "Organization registration, activation, suspension, subscription plans, billing, branding, domain mapping, global settings, and audit logs.",
  ),
  createLayerModule(
    "billing",
    "Billing",
    "Platform Foundation",
    "Organization subscriptions, invoices, billing cycles, plan changes, payment gateway status, tax metadata, and collection controls.",
    ["Account", "Plan", "Cycle", "Amount", "Status", "Renewal"],
  ),
  createLayerModule(
    "branding",
    "Branding",
    "Platform Foundation",
    "Organization logos, colors, sender identity, domains, public website theme, and branded communication settings.",
    ["Brand", "Domain", "Theme", "Sender", "Status", "Updated"],
  ),
  createLayerModule(
    "global-settings",
    "Global Settings",
    "Platform Foundation",
    "Global security, localization, notification, data-retention, billing, and platform policy configuration.",
    ["Setting", "Category", "Value", "Scope", "Status", "Updated"],
  ),
  createLayerModule(
    "audit-logs",
    "Audit Logs",
    "Platform Foundation",
    "Immutable operational audit trail for admin actions, access changes, exports, security events, and organization configuration changes.",
    ["Event", "Actor", "Entity", "Action", "Time", "Result"],
  ),
  {
    id: "authentication",
    title: "Authentication",
    group: "Access",
    metric: "9 policies",
    description:
      "CRM login, SSO readiness, MFA policy, session review, device controls, and organization-aware access rules.",
    filters: ["Policy", "Provider", "Status", "Scope"],
    columns: ["Control", "Provider", "Scope", "Owner", "Status", "Updated"],
    rows: [
      ["MFA policy", "Password + OTP", "Admins", "Security", "Active", "Today"],
      [
        "Google login",
        "OAuth",
        "Organization",
        "Platform",
        "Draft",
        "Yesterday",
      ],
      ["Session review", "JWT", "All users", "Security", "Active", "22 Jul"],
    ],
  },
  {
    id: "users",
    title: "Users",
    group: "Access",
    metric: "Live users",
    description:
      "Counselors, managers, branch admins, marketing, finance, call center, field agents, students, parents, roles, teams, and hierarchy.",
    filters: ["Role", "Team", "Branch", "Status"],
    columns: [
      "Name",
      "Email",
      "Role",
      "Department",
      "Last Login",
      "MFA Status",
      "Account Status",
      "Created Date",
    ],
    rows: [],
  },
  {
    id: "roles",
    title: "Roles",
    group: "Access",
    metric: "Live roles",
    description:
      "Role catalogue for super admins, organization admins, branch users, counselors, finance, marketing, parents, and students.",
    filters: ["Status", "Permission", "Module"],
    columns: ["Role", "Description", "Permissions", "Status", "Updated"],
    rows: [],
  },
  {
    id: "permissions",
    title: "Permissions",
    group: "Access",
    metric: "Live permissions",
    description:
      "Permission catalogue using resource:action rules for backend guards, CRM module access, and admin operations.",
    filters: ["Module", "Status"],
    columns: ["Permission", "Module", "Description", "Status", "Updated"],
    rows: [],
  },
  {
    id: "organizations",
    title: "Organizations",
    group: "Identity & Organization",
    metric: "12 organizations",
    description:
      "Universities, colleges, institutes, schools, coaching brands, franchises, domains, branding, channel settings, and activation lifecycle.",
    filters: ["Type", "Plan", "Status"],
    columns: [
      "Organization Name",
      "Organization Code",
      "Organization Type",
      "Primary Contact",
      "Email",
      "Phone",
      "Plan",
      "Subscription Status",
      "User Count",
      "Lead Usage",
      "Storage Usage",
      "Domain",
      "Created Date",
      "Last Activity",
      "Status",
    ],
    rows: [
      ["Webnza Coaching", "Coaching", "Enterprise", "Active"],
      ["North Branch College", "College", "Growth", "Active"],
      ["Bright Future School", "School", "Starter", "Trial"],
    ],
  },
  {
    id: "branches",
    title: "Branches",
    group: "Identity & Organization",
    metric: "API backed",
    description:
      "Branch offices or learning centers used for counselor assignment, lead ownership, admissions, finance, and operational visibility.",
    filters: ["City", "State", "Status"],
    columns: ["Branch", "Code", "City", "State", "Status"],
    rows: [
      ["Delhi Admissions", "DEL-ADM", "Delhi", "Delhi", "Active"],
      ["Mumbai Center", "MUM-CTR", "Mumbai", "Maharashtra", "Active"],
      ["Online Counseling", "ONL-COU", "Online", "India", "Active"],
    ],
  },
  {
    id: "departments",
    title: "Departments",
    group: "Identity & Organization",
    metric: "API backed",
    description:
      "Functional departments such as admissions, marketing, finance, academic operations, call center, and support.",
    filters: ["Function", "Status"],
    columns: ["Department", "Code", "Function", "Status", "Created"],
    rows: [
      ["Admissions", "ADM-DEPT", "Admissions", "Active", "22 Jul"],
      ["Finance", "FIN-DEPT", "Finance", "Active", "22 Jul"],
      ["Academic Ops", "OPS-DEPT", "Operations", "Active", "22 Jul"],
    ],
  },
  {
    id: "teams",
    title: "Teams",
    group: "Identity & Organization",
    metric: "API backed",
    description:
      "Operational teams for branch visibility, counselor queues, lead assignment, escalation, task routing, and reporting hierarchy.",
    filters: ["Department", "Branch", "Status"],
    columns: ["Team", "Code", "Department", "Branch", "Status"],
    rows: [
      ["North Counselors", "NORTH-COUN", "Admissions", "Delhi", "Active"],
      ["WhatsApp Desk", "WA-DESK", "Call Center", "Online", "Active"],
      ["Collections", "COLLECT", "Finance", "Mumbai", "Active"],
    ],
  },
  {
    id: "students",
    title: "Students",
    group: "Enrollment",
    metric: "1,284",
    description:
      "Complete student profile across personal, academic, parents, address, previous education, exams, preferences, documents, payments, and timeline.",
    filters: ["Grade", "Course", "Completeness", "Owner"],
    columns: [
      "Student",
      "Grade",
      "Course",
      "Completeness",
      "Guardian",
      "Status",
    ],
    rows: [
      [
        "Aarav Sharma",
        "Class 10",
        "JEE Foundation",
        "82%",
        "Nisha Sharma",
        "Active",
      ],
      ["Meera Iyer", "Class 12", "NEET Target", "76%", "Rahul Iyer", "Active"],
      ["Rhea Jain", "Class 10", "Maths", "94%", "Pooja Jain", "Active"],
    ],
  },
  {
    id: "call-center",
    title: "Call Center",
    group: "Growth",
    metric: "312 calls",
    description:
      "Incoming calls, outgoing calls, dialer queues, call recording references, disposition, call notes, follow-ups, and call analytics.",
    filters: ["Direction", "Disposition", "Agent", "Status"],
    columns: ["Call", "Lead", "Direction", "Disposition", "Agent", "Status"],
    rows: [
      [
        "CALL-1021",
        "Aarav Sharma",
        "Outbound",
        "Interested",
        "Ritika",
        "Completed",
      ],
      ["CALL-1022", "Meera Iyer", "Inbound", "Callback", "Sahil", "Open"],
      ["CALL-1023", "Kabir Khan", "Outbound", "No answer", "Dev", "Completed"],
    ],
  },
  {
    id: "whatsapp",
    title: "WhatsApp",
    group: "Growth",
    metric: "2,840",
    description:
      "WhatsApp templates, media, buttons, flows, bulk send, automation, delivery reports, and conversation history.",
    filters: ["Template", "Status", "Campaign", "Owner"],
    columns: ["Conversation", "Template", "Entity", "Status", "Owner", "Time"],
    rows: [
      [
        "WA-551",
        "Demo reminder",
        "Aarav Sharma",
        "Delivered",
        "System",
        "10:32 AM",
      ],
      ["WA-552", "Fee nudge", "Rhea Jain", "Read", "System", "09:00 AM"],
      [
        "WA-553",
        "Application help",
        "Meera Iyer",
        "Open",
        "Sahil",
        "Yesterday",
      ],
    ],
  },
  {
    id: "emails",
    title: "Emails",
    group: "Growth",
    metric: "18 campaigns",
    description:
      "Email templates, bulk mail, drip campaigns, open tracking, click tracking, bounces, unsubscribe, and campaign approval.",
    filters: ["Campaign", "Template", "Status", "Owner"],
    columns: [
      "Campaign",
      "Template",
      "Sent",
      "Open Rate",
      "Click Rate",
      "Status",
    ],
    rows: [
      ["NEET webinar", "Invite", "4,200", "38%", "9%", "Completed"],
      ["Application nudge", "Reminder", "1,140", "42%", "11%", "Active"],
      ["Fee reminder", "Payment", "860", "46%", "14%", "Active"],
    ],
  },
  {
    id: "sms",
    title: "SMS",
    group: "Growth",
    metric: "6,920",
    description:
      "OTP, transactional, promotional, bulk SMS, templates, provider callbacks, delivery reports, and compliance status.",
    filters: ["Type", "Template", "Status", "Provider"],
    columns: ["Message", "Type", "Provider", "Sent", "Delivered", "Status"],
    rows: [
      ["OTP login", "OTP", "MSG91", "1,240", "1,210", "Active"],
      ["Demo reminder", "Transactional", "Twilio", "840", "812", "Completed"],
      [
        "Scholarship promo",
        "Promotional",
        "MSG91",
        "2,400",
        "2,190",
        "Completed",
      ],
    ],
  },
  {
    id: "mobile-app",
    title: "Mobile App",
    group: "Operations",
    metric: "46 agents",
    description:
      "Counselor mobile dashboard, lead update, notes, voice notes, geo check-ins, tasks, calls, WhatsApp, payments, reports, and offline mode.",
    filters: ["Agent", "Mode", "Sync", "Status"],
    columns: ["Agent", "Workspace", "Leads", "Tasks", "Sync", "Status"],
    rows: [
      ["Ritika Jain", "Counselor", "42", "12", "Online", "Active"],
      ["Field Team A", "Field", "18", "7", "Offline ready", "Active"],
      ["Sahil Mehta", "Marketing", "31", "9", "Online", "Active"],
    ],
  },
  {
    id: "calendar",
    title: "Calendar",
    group: "Operations",
    metric: "94 events",
    description:
      "Counseling meetings, interviews, tasks, events, reminders, recurring schedules, and Google Calendar sync readiness.",
    filters: ["Type", "Owner", "Date", "Status"],
    columns: ["Event", "Type", "Entity", "Owner", "Time", "Status"],
    rows: [
      [
        "Parent counseling",
        "Meeting",
        "Aarav Sharma",
        "Ritika",
        "Today 5 PM",
        "Open",
      ],
      [
        "Interview round 1",
        "Interview",
        "APP-000144",
        "Ananya",
        "Tomorrow",
        "Open",
      ],
      ["NEET webinar", "Webinar", "Campaign", "Marketing", "Friday", "Active"],
    ],
  },
  {
    id: "tasks",
    title: "Tasks",
    group: "Operations",
    metric: "86",
    description:
      "Daily/weekly tasks, assignment, escalation, recurring reminders, comments, SLA, manager review, and task board operations.",
    filters: ["Assignee", "Priority", "SLA", "Status"],
    columns: ["Task", "Entity", "SLA", "Assignee", "Priority", "Status"],
    rows: [
      ["Call hot lead", "Aarav Sharma", "2h", "Ritika", "High", "Open"],
      [
        "Review documents",
        "APP-000144",
        "1d",
        "Ananya",
        "Urgent",
        "In progress",
      ],
      ["Send invoice", "RCPT-2193", "4h", "Dev", "Medium", "Open"],
    ],
  },
  {
    id: "documents",
    title: "Documents",
    group: "Operations",
    metric: "392 docs",
    description:
      "Upload, preview, verification, versioning, approval, OCR readiness, PDF/image/ZIP support, and document requirement tracking.",
    filters: ["Type", "Reviewer", "Status", "Entity"],
    columns: ["Document", "Entity", "Type", "Reviewer", "Version", "Status"],
    rows: [
      ["Birth proof", "Aarav Sharma", "ID", "Ananya", "v2", "Review"],
      ["Marksheet", "Meera Iyer", "Academic", "Dev", "v1", "Approved"],
      ["Address proof", "Rhea Jain", "KYC", "Sahil", "v1", "Pending"],
    ],
  },
  {
    id: "finance",
    title: "Finance",
    group: "Business",
    metric: "INR 31.8L",
    description:
      "Invoices, receipts, refunds, tax, ledger, collections, pending payments, finance reports, and refund approval operations.",
    filters: ["Type", "Status", "Owner", "Date"],
    columns: ["Item", "Type", "Amount", "Owner", "Due", "Status"],
    rows: [
      ["Ledger July", "Ledger", "INR 31.8L", "Finance", "Closed", "Ready"],
      ["Refund RF-102", "Refund", "INR 4,500", "Dev", "Today", "Review"],
      [
        "Pending fees",
        "Collection",
        "INR 7.2L",
        "Finance",
        "This week",
        "Open",
      ],
    ],
  },
  {
    id: "scholarship",
    title: "Scholarship",
    group: "Enrollment",
    metric: "21 cases",
    description:
      "Scholarship rules, eligibility, verification, approval, award amount, payment-plan impact, and audit trail.",
    filters: ["Rule", "Amount", "Reviewer", "Status"],
    columns: ["Case", "Student", "Rule", "Amount", "Reviewer", "Status"],
    rows: [
      ["SCH-101", "Sara Ali", "Merit", "25%", "Ananya", "Review"],
      ["SCH-102", "Vihaan Rao", "Need based", "15%", "Dev", "Approved"],
      ["SCH-103", "Kabir Khan", "Early bird", "10%", "Sahil", "Pending"],
    ],
  },
  {
    id: "interview",
    title: "Interviews",
    group: "Enrollment",
    metric: "33",
    description:
      "Interview schedule, interviewer, panel, result, remarks, score, offer recommendation, and admission handoff.",
    filters: ["Panel", "Result", "Owner", "Status"],
    columns: ["Interview", "Applicant", "Panel", "Time", "Result", "Status"],
    rows: [
      ["INT-401", "Meera Iyer", "Science", "Today 3 PM", "Pending", "Open"],
      ["INT-402", "Vihaan Rao", "NEET", "Tomorrow", "Recommended", "Completed"],
      ["INT-403", "Rhea Jain", "Maths", "Friday", "Pending", "Open"],
    ],
  },
  {
    id: "events",
    title: "Events",
    group: "Operations",
    metric: "14 events",
    description:
      "Education fairs, seminars, webinars, branch visits, registrations, attendance, QR check-in, and event lead capture.",
    filters: ["Type", "City", "Owner", "Status"],
    columns: [
      "Event",
      "Type",
      "Registrations",
      "Attendance",
      "Owner",
      "Status",
    ],
    rows: [
      ["NEET webinar", "Webinar", "640", "412", "Marketing", "Active"],
      ["Delhi education fair", "Fair", "220", "164", "Field Team", "Open"],
      ["Branch visit", "Visit", "82", "61", "Admissions", "Completed"],
    ],
  },
  {
    id: "field-force",
    title: "Field Force",
    group: "Operations",
    metric: "28 visits",
    description:
      "Geo tracking, GPS, route planning, daily visits, attendance, mileage, check-in/out, and location history.",
    filters: ["Agent", "Route", "City", "Status"],
    columns: ["Visit", "Agent", "Route", "Check-in", "Mileage", "Status"],
    rows: [
      ["VIS-701", "Field Team A", "Delhi North", "10:20 AM", "18 km", "Active"],
      ["VIS-702", "Field Team B", "Gurgaon", "11:00 AM", "22 km", "Completed"],
      ["VIS-703", "Ritika Jain", "Noida", "Pending", "0 km", "Open"],
    ],
  },
  {
    id: "analytics",
    title: "Analytics",
    group: "Business",
    metric: "12 models",
    description:
      "Lead funnel, admissions funnel, revenue, conversion, ROI, counselor productivity, campaign performance, forecasting, and predictive analytics.",
    filters: ["Metric", "Segment", "Owner", "Status"],
    columns: ["Model", "Segment", "Refresh", "Accuracy", "Owner", "Status"],
    rows: [
      [
        "Lead conversion",
        "All branches",
        "Hourly",
        "91%",
        "Analytics",
        "Ready",
      ],
      ["Revenue forecast", "Enterprise", "Daily", "87%", "Finance", "Ready"],
      ["Counselor SLA", "Admissions", "Hourly", "94%", "Ops", "Active"],
    ],
  },
  {
    id: "ai-features",
    title: "AI Features",
    group: "Business",
    metric: "8 assists",
    description:
      "CRM AI lead score, prediction, chatbot, conversation summaries, auto replies, next-best action, and follow-up suggestions.",
    filters: ["Feature", "Model", "Owner", "Status"],
    columns: ["Feature", "Use Case", "Model", "Owner", "Status", "Updated"],
    rows: [
      [
        "Lead score",
        "Prioritization",
        "Rules + AI",
        "Growth",
        "Draft",
        "Today",
      ],
      [
        "Conversation summary",
        "Counseling notes",
        "LLM",
        "Ops",
        "Active",
        "Yesterday",
      ],
      [
        "Follow-up suggestion",
        "Next action",
        "LLM",
        "Admissions",
        "Draft",
        "22 Jul",
      ],
    ],
  },
  {
    id: "integrations",
    title: "Integrations",
    group: "Business",
    metric: "19",
    description:
      "Facebook Lead Ads, Google Ads/Analytics, Meta Pixel, WhatsApp, Zoom/Meet, Razorpay, ERP, LMS, SIS, API keys, and webhooks.",
    filters: ["Provider", "Category", "Owner", "Status"],
    columns: [
      "Integration",
      "Category",
      "Provider",
      "Owner",
      "Last Sync",
      "Status",
    ],
    rows: [
      ["Razorpay", "Payment", "Razorpay", "Finance", "Today", "Active"],
      ["Meta leads", "Ads", "Meta", "Marketing", "Today", "Draft"],
      ["Google Meet", "Video", "Google", "Ops", "Yesterday", "Active"],
    ],
  },
  createLayerModule(
    "contacts",
    "Contacts",
    "Generic CRM",
    "Reusable people and organization contacts for enquiries, parents, guardians, students, vendors, partners, and counselors.",
    ["Contact", "Type", "Phone", "Email", "Owner", "Status"],
  ),
  createLayerModule(
    "lead-sources",
    "Lead Sources",
    "Generic CRM",
    "Website, ads, WhatsApp, walk-ins, referrals, imports, partners, API sources, and source ownership.",
    [
      "Source Name",
      "Code",
      "Category",
      "Active Leads",
      "Conversion Rate",
      "Cost",
      "Status",
    ],
  ),
  createLayerModule(
    "lead-stages",
    "Lead Stages",
    "Generic CRM",
    "Configurable enquiry stages, order, conversion flags, lost reasons, SLA policy, and pipeline movement rules.",
    [
      "Stage Name",
      "Order",
      "Category",
      "Active Lead Count",
      "Conversion Stage",
      "Lost Stage",
      "SLA",
      "Status",
    ],
  ),
  createLayerModule(
    "activities",
    "Activities",
    "Generic CRM",
    "Unified activity timeline for calls, messages, notes, stage movements, assignments, imports, and workflow actions.",
    ["Activity", "Entity", "Type", "Owner", "Time", "Status"],
  ),
  createLayerModule(
    "notes",
    "Notes",
    "Generic CRM",
    "Counselor notes, reviewer comments, student context notes, internal-only remarks, and audit-linked note history.",
    ["Note", "Entity", "Visibility", "Owner", "Updated", "Status"],
  ),
  createLayerModule(
    "follow-ups",
    "Follow-ups",
    "Generic CRM",
    "Follow-up queues, reminders, due dates, stale lead recycling, escalation, and completion tracking.",
    ["Follow-up", "Entity", "Due", "Owner", "Priority", "Status"],
  ),
  createLayerModule(
    "meetings",
    "Meetings",
    "Generic CRM",
    "Counseling meetings, demo sessions, parent meetings, branch visits, interviews, and calendar sync readiness.",
    ["Meeting", "Type", "Attendees", "Start", "Owner", "Status"],
  ),
  createLayerModule(
    "assignments",
    "Assignments",
    "Generic CRM",
    "Lead, task, application, and case assignment rules using users, teams, departments, branches, and capacity.",
    [
      "Lead",
      "Previous Owner",
      "New Owner",
      "Team",
      "Assignment Method",
      "Assigned By",
      "Assigned Date",
      "Assignment Reason",
    ],
  ),
  createLayerModule(
    "tags",
    "Tags",
    "Generic CRM",
    "Reusable tagging for leads, contacts, applications, students, documents, campaigns, and segmentation.",
    ["Tag", "Color", "Module", "Records", "Owner", "Status"],
  ),
  createLayerModule(
    "custom-fields",
    "Custom Fields",
    "Generic CRM",
    "Organization-defined fields, validation, module placement, reporting visibility, and payload mapping.",
    ["Field", "Module", "Type", "Required", "Status", "Updated"],
  ),
  createLayerModule(
    "imports-exports",
    "Imports And Exports",
    "Generic CRM",
    "CSV imports, duplicate handling, field mapping, export jobs, audit trail, and report download readiness.",
    ["Job", "Module", "Rows", "Owner", "Status", "Updated"],
  ),
  createLayerModule(
    "academic-sessions",
    "Academic Sessions",
    "Education",
    "Academic terms, batches, live classes, AI tutor schedules, holidays, and operational calendars.",
    ["Session", "Program", "Batch", "Start", "Owner", "Status"],
  ),
  createLayerModule(
    "programs",
    "Programs",
    "Education",
    "Programs such as JEE, NEET, UPSC, school tutoring, study abroad, foundation batches, and long-term learning tracks.",
    ["Program", "Category", "Duration", "Subjects", "Owner", "Status"],
  ),
  createLayerModule(
    "courses",
    "Courses",
    "Education",
    "Courses, subjects, topics, curriculum mapping, learning outcomes, pricing, and enrollment readiness.",
    ["Course", "Program", "Subjects", "Level", "Fee", "Status"],
  ),
  createLayerModule(
    "specializations",
    "Specializations",
    "Education",
    "Specializations, streams, exam tracks, electives, and focused learning paths inside a program.",
    ["Specialization", "Program", "Track", "Courses", "Owner", "Status"],
  ),
  createLayerModule(
    "enrollment",
    "Enrollment",
    "Education",
    "Admission-to-student conversion, batch allocation, learning entitlement provisioning, and portal activation.",
    ["Enrollment", "Student", "Program", "Batch", "Access", "Status"],
  ),
  createLayerModule(
    "fees",
    "Fees",
    "Education",
    "Application fees, admission fees, installments, waivers, scholarships, receipts, refunds, dues, and ledgers.",
    ["Fee", "Student", "Amount", "Due", "Status", "Ledger"],
  ),
  createLayerModule(
    "landing-pages",
    "Landing Pages",
    "Growth & Automation",
    "Campaign landing pages, forms, UTM capture, conversion tags, audience mapping, and lead capture links.",
    ["Page", "Campaign", "Source", "Conversions", "Owner", "Status"],
  ),
  createLayerModule(
    "lead-scoring",
    "Lead Scoring",
    "Growth & Automation",
    "Rule-based and AI-assisted scoring for lead temperature, intent, SLA risk, source quality, and next-best action.",
    ["Model", "Signal", "Weight", "Accuracy", "Owner", "Status"],
  ),
  createLayerModule(
    "marketing-attribution",
    "Marketing Attribution",
    "Growth & Automation",
    "Source ROI, UTM inventory, funnel contribution, ad spend, conversion tags, and campaign performance attribution.",
    ["Attribution", "Source", "Spend", "Revenue", "ROI", "Status"],
  ),
  createLayerModule(
    "telephony",
    "Telephony",
    "Growth & Automation",
    "Dialer integration, inbound/outbound calls, recordings, dispositions, queue automation, and call analytics.",
    ["Queue", "Provider", "Calls", "Recording", "Owner", "Status"],
  ),
  createLayerModule(
    "chatbots",
    "Chatbots",
    "Growth & Automation",
    "Website, WhatsApp, and in-app bots for enquiry capture, FAQ, qualification, scheduling, and AI handoff.",
    ["Bot", "Channel", "Intent", "Automation", "Owner", "Status"],
  ),
  {
    id: "security",
    title: "Security",
    group: "Access",
    metric: "17 controls",
    description:
      "RBAC, audit logs, activity logs, IP restrictions, data masking, encryption policy, backups, 2FA, SSO, and admin exports.",
    filters: ["Control", "Scope", "Owner", "Status"],
    columns: ["Control", "Scope", "Policy", "Owner", "Status", "Updated"],
    rows: [
      ["Data masking", "PII", "Role based", "Security", "Draft", "Today"],
      [
        "IP restriction",
        "Admin",
        "Office/VPN",
        "Security",
        "Review",
        "Yesterday",
      ],
      [
        "Audit export",
        "Organization",
        "Monthly",
        "Compliance",
        "Active",
        "22 Jul",
      ],
    ],
  },
];

export const productionModuleIds = new Set([
  "leads",
  "applications",
  "tasks",
  "campaigns",
  "communications",
  "notifications",
  "organizations",
  "branches",
  "departments",
  "teams",
]);

export const workflowModuleIds = new Set([
  "admissions",
  "automation",
  "payments",
  "reports",
  "learning",
  "settings",
  "analytics",
  "security",
]);

export function getModuleStatus(id: string): ModuleStatus {
  if (productionModuleIds.has(id)) return "Active";
  if (workflowModuleIds.has(id)) return "Configured";
  return "Setup";
}

export function enrichModule(module: AdminModule): AdminModule {
  return {
    ...module,
    actions: module.actions ??
      moduleActions[module.id] ?? ["Create", "Assign", "Export", "Audit"],
    icon: module.icon ?? moduleIcons[module.id] ?? "dashboard",
    status: module.status ?? getModuleStatus(module.id),
  };
}

export const allModules = [...modules, ...extraModules].map(enrichModule);

export const moduleMap = Object.fromEntries(
  allModules.map((module) => [module.id, module]),
);

export function getModuleHref(id: string) {
  return id === "dashboard" ? "/" : `/${id}`;
}

export function resolveRouteModuleId(
  pathname: string | null,
  fallback: string,
) {
  const segment = pathname?.split("/").filter(Boolean)[0] ?? "";
  if (!segment) return "dashboard";
  if (segment === "organizations") return "organizations";
  if (moduleMap[segment]) return segment;
  if (fallback === "organizations") return "organizations";
  return moduleMap[fallback] ? fallback : "dashboard";
}
