export enum AnalyticsEventType {
  APP_OPENED = 'APP_OPENED',
  APP_BACKGROUND = 'APP_BACKGROUND',

  ONBOARDING_STARTED = 'ONBOARDING_STARTED',
  ONBOARDING_COMPLETED = 'ONBOARDING_COMPLETED',

  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',

  PROFILE_CREATED = 'PROFILE_CREATED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  PROFILE_VERIFIED = 'PROFILE_VERIFIED',

  SEARCH_PERFORMED = 'SEARCH_PERFORMED',
  FILTER_APPLIED = 'FILTER_APPLIED',
  PROFILE_IMPRESSION = 'PROFILE_IMPRESSION',
  PROFILE_VIEWED = 'PROFILE_VIEWED',

  SHORTLIST_ADDED = 'SHORTLIST_ADDED',
  SHORTLIST_REMOVED = 'SHORTLIST_REMOVED',

  MATCH_CREATED = 'MATCH_CREATED',
  MATCH_REQUEST_SENT = 'MATCH_REQUEST_SENT',
  MATCH_ACCEPTED = 'MATCH_ACCEPTED',

  CHAT_OPENED = 'CHAT_OPENED',
  CHAT_STARTED = 'CHAT_STARTED',
  CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT',
  CALL_INITIATED = 'CALL_INITIATED',

  SUBSCRIPTION_VIEWED = 'SUBSCRIPTION_VIEWED',
  SUBSCRIPTION_PURCHASED = 'SUBSCRIPTION_PURCHASED',
  BOOST_PURCHASED = 'BOOST_PURCHASED',

  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  REPORT_SUBMITTED = 'REPORT_SUBMITTED',
  USER_BLOCKED = 'USER_BLOCKED',

  NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED',
  NOTIFICATION_OPENED = 'NOTIFICATION_OPENED',
}

export enum AnalyticsPlatform {
  WEB = 'web',
  ANDROID = 'android',
  IOS = 'ios',
  API = 'api',
}

export enum AnalyticsFunnelStage {
  AWARENESS = 'AWARENESS',
  DISCOVERY = 'DISCOVERY',
  INTEREST = 'INTEREST',
  MATCHING = 'MATCHING',
  CONVERSATION = 'CONVERSATION',
  MONETIZATION = 'MONETIZATION',
  RETENTION = 'RETENTION',
}

export enum AnalyticsGroupBy {
  EVENT_TYPE = 'eventType',
  PLATFORM = 'platform',
  SOURCE = 'source',
  CAMPAIGN = 'campaign',
  COUNTRY = 'country',
  CITY = 'city',
  FUNNEL_STAGE = 'funnelStage',
}
