import { createBaseStyles } from '@/core/theme/baseStyles';
import { Theme } from '@/core/theme/types';
import { Platform, StyleSheet } from 'react-native';

export const matchDetailStyles = (
  theme: Theme,
  base: ReturnType<typeof createBaseStyles>
) =>
  StyleSheet.create({
    container: StyleSheet.flatten(base.container),

    // ─── Carousel ─────────────────────────────────────────────────────────
    carouselWrapper: { position: 'relative' },
    photo: {
      width: '100%',
      height: 420,
    },
    photoPrivacyFrame: {
      width: '100%',
      height: 420,
      position: 'relative',
      overflow: 'hidden',
      backgroundColor: theme.colors.backgroundLight,
    },
    photoPrivacyOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.overlayDark,
      gap: 8,
    },
    photoPrivacyText: {
      color: theme.colors.white,
      fontSize: 13,
      fontWeight: '700',
    },
    carouselScrim: {
      position: 'absolute',
      bottom: 0,
      width: '100%',
      height: 150,
      backgroundColor: theme.colors.overlayDark,
      opacity: 0.48,
    },
    counterPill: {
      position: 'absolute',
      top: 14,
      right: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: theme.colors.overlayDark,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 20,
    },
    counterText: {
      color: theme.colors.white,
      fontSize: 12,
      fontWeight: '700',
    },
    dots: {
      position: 'absolute',
      bottom: 68,
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 6,
    },
    dot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.overlayDark,
    },
    dotActive: {
      backgroundColor: theme.colors.surface,
      width: 20,
    },

    // ─── Hero Overlay ─────────────────────────────────────────────────────
    heroOverlay: {
      position: 'absolute',
      bottom: 16,
      left: 16,
      right: 16,
    },
    onlinePill: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: theme.colors.success,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      marginBottom: 8,
      gap: 5,
    },
    onlineDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.success,
    },
    onlinePillText: {
      color: theme.colors.white,
      fontSize: 11,
      fontWeight: '700',
    },
    heroName: {
      fontSize: 26,
      fontWeight: '800',
      color: theme.colors.white,
      marginBottom: 4,
      textShadowColor: theme.colors.overlayDark,
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 3,
    },
    heroLocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    heroLocation: {
      fontSize: 13,
      color: theme.colors.white,
      textShadowColor: theme.colors.overlayDark,
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },

    // ─── Match Score ──────────────────────────────────────────────────────
    matchScoreBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      gap: 12,
    },
    matchScoreLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    matchScoreIconWrapper: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    matchScoreLabel: {
      fontSize: 12,
      color: theme.colors.textMuted,
    },
    matchScoreValue: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    matchScoreDivider: {
      width: StyleSheet.hairlineWidth,
      height: 36,
      backgroundColor: theme.colors.divider,
    },

    // ─── Chips ────────────────────────────────────────────────────────────
    compatibilityHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 16,
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    compatibilityPerson: {
      flex: 1,
      alignItems: 'center',
      gap: 7,
      minWidth: 0,
    },
    compareAvatar: {
      width: 54,
      height: 54,
      borderRadius: 27,
      backgroundColor: theme.colors.backgroundLight,
    },
    compareAvatarFallback: {
      width: 54,
      height: 54,
      borderRadius: 27,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    compareName: {
      maxWidth: '100%',
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textSecondary,
      textAlign: 'center',
    },
    compatibilityScoreBadge: {
      width: 86,
      minHeight: 72,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      backgroundColor: theme.colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
      paddingHorizontal: 8,
      paddingVertical: 10,
    },
    compatibilityScoreValue: {
      fontSize: 22,
      fontWeight: '900',
      color: theme.colors.primary,
    },
    compatibilityScoreLabel: {
      marginTop: 2,
      fontSize: 10,
      fontWeight: '700',
      color: theme.colors.textMuted,
      textTransform: 'uppercase',
      textAlign: 'center',
      letterSpacing: 0.6,
    },
    compareRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      gap: 10,
    },
    compareRowLast: {
      borderBottomWidth: 0,
    },
    compareValue: {
      flex: 1,
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      textAlign: 'center',
      lineHeight: 17,
    },
    compareField: {
      width: 118,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
    },
    compareLabelRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 6,
    },
    compareLabel: {
      fontSize: 11,
      color: theme.colors.textMuted,
      textAlign: 'center',
      flex: 1,
    },
    compareWeight: {
      fontSize: 10,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    preferenceTrack: {
      width: '100%',
      height: 7,
      borderRadius: 4,
      overflow: 'hidden',
      backgroundColor: theme.colors.backgroundLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    preferenceFill: {
      height: '100%',
      borderRadius: 4,
    },
    preferenceFill0: { width: '0%', backgroundColor: theme.colors.error },
    preferenceFill5: { width: '5%', backgroundColor: theme.colors.error },
    preferenceFill10: { width: '10%', backgroundColor: theme.colors.error },
    preferenceFill15: { width: '15%', backgroundColor: theme.colors.error },
    preferenceFill20: { width: '20%', backgroundColor: theme.colors.error },
    preferenceFill25: { width: '25%', backgroundColor: theme.colors.error },
    preferenceFill30: { width: '30%', backgroundColor: theme.colors.error },
    preferenceFill35: { width: '35%', backgroundColor: theme.colors.error },
    preferenceFill40: { width: '40%', backgroundColor: theme.colors.error },
    preferenceFill45: { width: '45%', backgroundColor: theme.colors.error },
    preferenceFill50: { width: '50%', backgroundColor: theme.colors.warning },
    preferenceFill55: { width: '55%', backgroundColor: theme.colors.warning },
    preferenceFill60: { width: '60%', backgroundColor: theme.colors.warning },
    preferenceFill65: { width: '65%', backgroundColor: theme.colors.warning },
    preferenceFill70: { width: '70%', backgroundColor: theme.colors.warning },
    preferenceFill75: { width: '75%', backgroundColor: theme.colors.warning },
    preferenceFill80: { width: '80%', backgroundColor: theme.colors.success },
    preferenceFill85: { width: '85%', backgroundColor: theme.colors.success },
    preferenceFill90: { width: '90%', backgroundColor: theme.colors.success },
    preferenceFill95: { width: '95%', backgroundColor: theme.colors.success },
    preferenceFill100: { width: '100%', backgroundColor: theme.colors.success },
    preferenceScoreText: {
      fontSize: 10,
      fontWeight: '800',
      color: theme.colors.textSecondary,
    },

    chipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 14,
      backgroundColor: theme.colors.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: theme.colors.primaryLight,
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    chipText: {
      fontSize: 12,
      color: theme.colors.primary,
      fontWeight: '600',
    },

    // ─── Section ──────────────────────────────────────────────────────────
    section: {
      backgroundColor: theme.colors.surface,
      marginTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      overflow: 'hidden',
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    sectionIconWrapper: {
      width: 30,
      height: 30,
      borderRadius: 9,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    sectionBody: {
      paddingHorizontal: 16,
    },

    // ─── Row ──────────────────────────────────────────────────────────────
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 13,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    rowLast: { borderBottomWidth: 0 },
    rowLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    label: {
      fontSize: 13,
      color: theme.colors.textMuted,
    },
    value: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      textAlign: 'right',
      flex: 1,
      marginLeft: 16,
    },

    // ─── About ────────────────────────────────────────────────────────────
    aboutText: {
      fontSize: 14,
      color: theme.colors.textBody,
      lineHeight: 22,
      paddingVertical: 14,
    },

    // ─── Safety ───────────────────────────────────────────────────────────
    contactRevealBox: {
      alignItems: 'center',
      paddingVertical: 18,
      gap: 10,
    },
    contactRevealIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    contactRevealTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    contactRevealText: {
      maxWidth: 310,
      fontSize: 13,
      lineHeight: 19,
      color: theme.colors.textMuted,
      textAlign: 'center',
    },
    contactRevealError: {
      maxWidth: 310,
      fontSize: 12,
      lineHeight: 18,
      color: theme.colors.error,
      textAlign: 'center',
    },
    contactRevealButton: {
      minHeight: 42,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      borderRadius: 22,
      paddingHorizontal: 18,
      backgroundColor: theme.colors.primary,
    },
    contactRevealButtonDisabled: {
      opacity: 0.55,
    },
    contactRevealButtonText: {
      fontSize: 13,
      fontWeight: '800',
      color: theme.colors.white,
    },

    safetyActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      paddingVertical: 14,
    },
    safetyButton: {
      flex: 1,
      minWidth: 142,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      backgroundColor: theme.colors.backgroundLight,
      paddingVertical: 12,
    },
    safetyButtonDanger: {
      borderColor: theme.colors.error,
      backgroundColor: theme.colors.errorLight,
    },
    safetyButtonText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.textSecondary,
    },
    safetyButtonTextDanger: { color: theme.colors.error },

    // ─── CTA ──────────────────────────────────────────────────────────────
    cta: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 16,
      backgroundColor: theme.colors.surface,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      gap: 12,
      ...Platform.select({
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: -2 },
          shadowOpacity: 0.06,
          shadowRadius: 8,
        },
        android: { elevation: 12 },
        web: {},
      }),
    },
    ctaOutline: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
      borderRadius: 30,
      paddingVertical: 13,
    },
    ctaOutlineText: {
      color: theme.colors.primary,
      fontWeight: '700',
      fontSize: 14,
    },
    ctaPrimary: {
      flex: 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: theme.colors.primary,
      borderRadius: 30,
      paddingVertical: 13,
      ...Platform.select({
        android: { elevation: 4 },
        ios: {
          shadowColor: theme.colors.primary,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.3,
          shadowRadius: 8,
        },
        web: {},
      }),
    },
    ctaPrimaryDisabled: {
      backgroundColor: theme.colors.textMuted,
      elevation: 0,
      shadowOpacity: 0,
    },
    ctaPrimaryText: {
      color: theme.colors.white,
      fontWeight: '800',
      fontSize: 14,
    },

    // ─── Empty ────────────────────────────────────────────────────────────
    footerSpacer: {
      height: StyleSheet.flatten(base.footer).height,
    },
    emptyContainer: {
      flex: 1,
      minHeight: 360,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
      gap: 16,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
    emptyAction: {
      marginTop: 4,
      borderRadius: 22,
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 22,
      paddingVertical: 11,
    },
    emptyActionText: {
      color: theme.colors.white,
      fontSize: 14,
      fontWeight: '800',
    },
  });
