import {
  Countries,
  EatingHabits,
  DrinkingHabits,
  Genders,
  ManglikStatuses,
  MaritalStatuses,
  SmokingHabits,
  ProfileFors,
  Hours,
  Minutes,
  Periods,
  Qualifications,
  OccupationTypes,
  Religions,
  Castes,
  PersonalityBadges,
} from '@/core/types';
import { ProfileData, Siblings } from './EditProfile.types';

// ─── Defaults ─────────────────────────────────────────────────────────────────
export const INITIAL_SIBLINGS: Siblings = {
  brothersCount: 0,
  sistersCount: 0,
  marriedBrothersCount: 0,
  marriedSistersCount: 0,
  details: [],
  note: '',
};

export const INITIAL_PROFILE: ProfileData = {
  personal: {
    profileFor: ProfileFors.SELF,
    firstName: '',
    lastName: '',
    gender: Genders.MALE,
    dateOfBirth: '',
    maritalStatus: MaritalStatuses.NEVER_MARRIED,
    willingToRelocate: false,
    hasChildren: false,
    sonsCount: 0,
    daughtersCount: 0,
    manglikStatus: ManglikStatuses.NON_MANGLIK,
    smoking: SmokingHabits.NON_SMOKER,
    drinking: DrinkingHabits.NON_DRINKER,
    eating: EatingHabits.VEGETARIAN,
    hobbies: [],
    personalityBadges: [
      PersonalityBadges.FAMILY_ORIENTED,
      PersonalityBadges.MARRIAGE_FOCUSED,
      PersonalityBadges.SUPPORTIVE,
    ],
    languages: [],
    aboutMe: '',
    placeOfBirth: {
      city: '',
      state: '',
      country: Countries.INDIA,
    },
    timeOfBirth: {
      hour: Hours.ONE,
      minute: Minutes.ZERO,
      period: Periods.AM,
    },
    religion: Religions.HINDU,
    caste: Castes.GENERAL,
    subCast: '',
    gotra: '',
    rashi: '',
    nakshatra: '',
    kundliFileUrl: '',
    country: Countries.INDIA,
    state: '',
    city: '',
    citizenship: '',
    isNri: false,
    residencyCountry: Countries.INDIA,
    visaStatus: '',
    abroadSince: '',
    motherTongue: '',
  },
  physical: {
    height: '',
    weight: '',
    bloodGroup: undefined,
    bodyType: undefined,
    complexion: undefined,
    disabilityStatus: false,
    disabilityNote: '',
  },
  education: {
    qualification: Qualifications.BA,
    field: '',
    university: '',
    occupationType: OccupationTypes.BUSINESS,
    occupation: '',
    companyName: '',
    jobRole: '',
    annualIncomeAmount: 0,
  },
  family: {
    fatherName: '',
    motherName: '',
    fatherOccupation: '',
    motherOccupation: '',
    familyType: undefined,
    familyStatus: undefined,
    familyValues: undefined,
    siblings: INITIAL_SIBLINGS,
  },
  images: [],
};
