import { ProfileData, Siblings } from './EditProfile.types';

// ─── Defaults ─────────────────────────────────────────────────────────────────
export const INITIAL_SIBLINGS: Siblings = {
  brothersCount: 0,
  sistersCount: 0,
  marriedBrothersCount: 0,
  marriedSistersCount: 0,
  details: [],
  note: '',
};

export const INITIAL_PROFILE: ProfileData = {
  personal: {
    firstName: '',
    lastName: '',
    dateOfBirth: '',
    maritalStatus: 'never_married',
    willingToRelocate: false,
    hasChildren: false,
    sonsCount: 0,
    daughtersCount: 0,
    manglikStatus: 'non_manglik',
    smoking: 'non_smoker',
    drinking: 'non_drinker',
    diet: 'vegetarian',
    hobbies: [],
    languages: [],
    aboutMe: '',
    placeOfBirth: {
      city: '',
      state: '',
      country: '',
    },
    timeOfBirth: {
      hour: undefined,
      minute: undefined,
      period: undefined,
    },
    subCast: '',
    gotra: '',
    rashi: '',
    nakshatra: '',
    kundliFileUrl: '',
    country: '',
    state: '',
    citizenship: '',
    motherTongue: '',
  },
  physical: {
    heightLabel: '',
    weightKg: '',
    bloodGroup: undefined,
    bodyType: undefined,
    complexion: undefined,
    disabilityStatus: false,
    disabilityNote: '',
  },
  education: {
    qualification: '',
    field: '',
    university: '',
    occupationType: undefined,
    occupation: '',
    companyName: '',
    jobRole: '',
    annualIncomeAmount: '',
  },
  family: {
    fatherName: '',
    motherName: '',
    fatherOccupation: '',
    motherOccupation: '',
    familyType: undefined,
    familyStatus: undefined,
    familyValues: undefined,
    siblings: INITIAL_SIBLINGS,
  },
  images: [],
};
