import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { User, UserSchema } from '@/modules/auth/schemas/user.schema';
import { LearningController } from './controllers/learning.controller';
import { StudentsController } from './controllers/students.controller';
import { LearningService } from './services/learning.service';
import { AgePolicyService } from './services/age-policy.service';
import {
  AcademicBoard,
  AcademicBoardSchema,
  AcademicLevel,
  AcademicLevelSchema,
  AiTutorMessage,
  AiTutorMessageSchema,
  AiTutorSession,
  AiTutorSessionSchema,
  Assessment,
  AssessmentAnswer,
  AssessmentAnswerSchema,
  AssessmentAttempt,
  AssessmentAttemptSchema,
  AssessmentResult,
  AssessmentResultSchema,
  AssessmentSchema,
  Classroom,
  ClassroomFile,
  ClassroomFileSchema,
  ClassroomMessage,
  ClassroomMessageSchema,
  ClassroomSchema,
  Course,
  CourseSchema,
  Curriculum,
  CurriculumSchema,
  Grade,
  GradeSchema,
  Institution,
  InstitutionSchema,
  LearningEntitlement,
  LearningEntitlementSchema,
  LearningRecommendation,
  LearningRecommendationSchema,
  LearningSchedule,
  LearningScheduleSchema,
  StudyPlan,
  StudyPlanSchema,
  ParentProfile,
  ParentProfileSchema,
  ParentStudentRelationship,
  ParentStudentRelationshipSchema,
  ParentalControl,
  ParentalControlSchema,
  Question,
  QuestionBank,
  QuestionBankSchema,
  QuestionSchema,
  StudentInvitation,
  StudentInvitationSchema,
  StudentAcademicRecord,
  StudentAcademicRecordSchema,
  StudentProfile,
  StudentProfileSchema,
  StudentSubjectEnrollment,
  StudentSubjectEnrollmentSchema,
  StudentTopicProgress,
  StudentTopicProgressSchema,
  Subject,
  SubjectSchema,
  Stream,
  StreamSchema,
  Topic,
  TopicSchema,
  University,
  UniversitySchema,
  SafetyEvent,
  SafetyEventSchema,
  TutorAvailability,
  TutorAvailabilitySchema,
  TutorProfile,
  TutorProfileSchema,
  TutorSessionNote,
  TutorSessionNoteSchema,
} from './schemas/learning.schemas';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: StudentProfile.name, schema: StudentProfileSchema },
      { name: ParentProfile.name, schema: ParentProfileSchema },
      {
        name: ParentStudentRelationship.name,
        schema: ParentStudentRelationshipSchema,
      },
      { name: StudentInvitation.name, schema: StudentInvitationSchema },
      { name: ParentalControl.name, schema: ParentalControlSchema },
      { name: StudentAcademicRecord.name, schema: StudentAcademicRecordSchema },
      { name: AcademicBoard.name, schema: AcademicBoardSchema },
      { name: AcademicLevel.name, schema: AcademicLevelSchema },
      { name: Grade.name, schema: GradeSchema },
      { name: Stream.name, schema: StreamSchema },
      { name: Course.name, schema: CourseSchema },
      { name: Institution.name, schema: InstitutionSchema },
      { name: University.name, schema: UniversitySchema },
      { name: Subject.name, schema: SubjectSchema },
      { name: Topic.name, schema: TopicSchema },
      { name: Curriculum.name, schema: CurriculumSchema },
      { name: StudyPlan.name, schema: StudyPlanSchema },
      {
        name: StudentSubjectEnrollment.name,
        schema: StudentSubjectEnrollmentSchema,
      },
      { name: LearningSchedule.name, schema: LearningScheduleSchema },
      { name: LearningEntitlement.name, schema: LearningEntitlementSchema },
      { name: AiTutorSession.name, schema: AiTutorSessionSchema },
      { name: AiTutorMessage.name, schema: AiTutorMessageSchema },
      { name: QuestionBank.name, schema: QuestionBankSchema },
      { name: Question.name, schema: QuestionSchema },
      { name: Assessment.name, schema: AssessmentSchema },
      { name: AssessmentAttempt.name, schema: AssessmentAttemptSchema },
      { name: AssessmentAnswer.name, schema: AssessmentAnswerSchema },
      { name: AssessmentResult.name, schema: AssessmentResultSchema },
      {
        name: StudentTopicProgress.name,
        schema: StudentTopicProgressSchema,
      },
      {
        name: LearningRecommendation.name,
        schema: LearningRecommendationSchema,
      },
      { name: Classroom.name, schema: ClassroomSchema },
      { name: ClassroomMessage.name, schema: ClassroomMessageSchema },
      { name: ClassroomFile.name, schema: ClassroomFileSchema },
      { name: TutorProfile.name, schema: TutorProfileSchema },
      { name: TutorAvailability.name, schema: TutorAvailabilitySchema },
      { name: TutorSessionNote.name, schema: TutorSessionNoteSchema },
      { name: SafetyEvent.name, schema: SafetyEventSchema },
      { name: User.name, schema: UserSchema },
    ]),
  ],
  controllers: [StudentsController, LearningController],
  providers: [LearningService, AgePolicyService],
  exports: [LearningService, AgePolicyService],
})
export class LearningModule {}
