import { createBaseStyles } from '@/core/theme/baseStyles';
import { Theme } from '@/core/theme/types';
import { Platform, StyleSheet } from 'react-native';

export const membershipStyles = (
  theme: Theme,
  base: ReturnType<typeof createBaseStyles>
) =>
  StyleSheet.create({
    container: StyleSheet.flatten(base.container),
    scroll: {
      ...StyleSheet.flatten(base.scrollContentCompact),
      paddingHorizontal: 16,
      paddingTop: 0,
      paddingBottom: 10,
    },

    // ─── Hero ─────────────────────────────────────────────────────────────
    heroCard: {
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      padding: 20,
      marginTop: 20,
      marginBottom: 20,
      overflow: 'hidden',
    },
    heroBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.colors.accent,
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      marginBottom: 12,
    },
    heroBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.colors.white,
      letterSpacing: 0.5,
    },
    heroTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: theme.colors.white,
      marginBottom: 4,
    },
    // Fixed: accentLight → rgba on primary background
    heroSubtitle: {
      fontSize: 13,
      color: theme.colors.accentLight,
      lineHeight: 19,
      marginBottom: 16,
    },
    heroStats: {
      flexDirection: 'row',
      gap: 12,
    },
    heroStat: {
      backgroundColor: theme.colors.black + '0D', // 5% opacity on black for contrast on any background
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 7,
      alignItems: 'center',
    },
    heroStatValue: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.colors.white,
    },
    heroStatLabel: {
      fontSize: 10,
      color: theme.colors.accentLight,
      marginTop: 1,
    },

    // ─── Tabs ─────────────────────────────────────────────────────────────
    tabs: {
      flexDirection: 'row',
      backgroundColor: theme.colors.backgroundLight,
      borderRadius: 12,
      padding: 4,
      marginBottom: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    tab: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      borderRadius: 9,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 6,
    },
    activeTab: {
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
      ...Platform.select({
        android: { elevation: 3 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.08,
          shadowRadius: 4,
        },
        web: {},
      }),
    },
    tabText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      fontWeight: '500',
    },
    activeTabText: {
      color: theme.colors.primary,
      fontWeight: '700',
    },

    // ─── Refund Banner ────────────────────────────────────────────────────
    refundBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.successLight,
      borderRadius: 12,
      padding: 12,
      marginBottom: 20,
      gap: 10,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.success,
    },
    refundIcon: { fontSize: 20 },
    refundText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.success,
    },
    refundSub: {
      fontSize: 11,
      color: theme.colors.success,
      marginTop: 1,
    },

    // ─── Plan Cards ───────────────────────────────────────────────────────
    planRow: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      marginBottom: 20,
      gap: 8,
    },
    planCard: {
      width: 132,
      minHeight: 150,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      borderRadius: 16,
      padding: 12,
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      position: 'relative',
      ...Platform.select({
        android: { elevation: 1 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.05,
          shadowRadius: 4,
        },
        web: {},
      }),
    },
    planCardActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primaryLight,
      ...Platform.select({
        android: { elevation: 5 },
        ios: {
          shadowColor: theme.colors.primary,
          shadowOffset: { width: 0, height: 3 },
          shadowOpacity: 0.2,
          shadowRadius: 6,
        },
        web: {},
      }),
    },
    popularBadge: {
      position: 'absolute',
      top: -11,
      backgroundColor: theme.colors.accent,
      paddingHorizontal: 9,
      paddingVertical: 3,
      borderRadius: 20,
    },
    popularBadgeText: {
      color: theme.colors.white,
      fontSize: 10,
      fontWeight: '700',
    },
    planName: {
      fontSize: 12,
      fontWeight: '700',
      // Fixed: textBody → textSecondary
      color: theme.colors.textSecondary,
      marginTop: 10,
    },
    planNameActive: { color: theme.colors.primary },
    planPrice: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      marginTop: 4,
    },
    planPriceActive: { color: theme.colors.primary },
    planDuration: {
      fontSize: 10,
      color: theme.colors.textMuted,
      marginBottom: 4,
      textAlign: 'center',
    },
    planMetaLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: theme.colors.success,
      textAlign: 'center',
      marginBottom: 2,
    },
    planMetaMuted: {
      fontSize: 9,
      lineHeight: 12,
      color: theme.colors.textMuted,
      textAlign: 'center',
      marginBottom: 6,
    },
    radioOuter: {
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 2,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 4,
      marginBottom: 6,
    },
    radioOuterActive: { borderColor: theme.colors.primary },
    radioInner: {
      width: 9,
      height: 9,
      borderRadius: 5,
      backgroundColor: theme.colors.primary,
    },

    // ─── Feature Table ────────────────────────────────────────────────────
    featureTableCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      marginBottom: 20,
      ...Platform.select({
        android: { elevation: 1 },
        ios: {},
        web: {},
      }),
    },
    featureTableHeader: {
      flexDirection: 'row',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderBottomWidth: 2,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primaryLight,
    },
    featureHeaderLabel: {
      flex: 1,
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    featureHeaderCol: {
      flex: 1,
      textAlign: 'center',
      fontSize: 11,
      color: theme.colors.textSecondary,
      fontWeight: '600',
    },
    featureHeaderColActive: {
      color: theme.colors.primary,
      fontWeight: '800',
    },
    featureRow: {
      flexDirection: 'row',
      paddingVertical: 13,
      paddingHorizontal: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      alignItems: 'center',
    },
    featureRowLast: { borderBottomWidth: 0 },
    featureLabel: {
      flex: 1,
      fontSize: 13,
      // Fixed: textBody → textSecondary
      color: theme.colors.textSecondary,
    },
    featureValues: {
      flexDirection: 'row',
      width: '45%',
      justifyContent: 'space-around',
    },
    featureCell: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 3,
      borderRadius: 6,
      marginHorizontal: 2,
    },
    featureCellActive: { backgroundColor: theme.colors.primaryLight },
    featureValue: {
      fontSize: 12,
      fontWeight: '700',
      // Fixed: textBody → textSecondary
      color: theme.colors.textSecondary,
      textAlign: 'center',
    },
    featureValueActive: { color: theme.colors.primary },
    featureCheck: { color: theme.colors.success },
    featureZero: { color: theme.colors.textMuted },

    boostCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      padding: 14,
      marginBottom: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
      gap: 12,
    },
    boostIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
    },
    boostCopy: {
      flex: 1,
    },
    boostTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    boostSubtitle: {
      fontSize: 12,
      lineHeight: 17,
      color: theme.colors.textSecondary,
      marginTop: 2,
    },
    boostButton: {
      borderRadius: 18,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: theme.colors.primary,
    },
    boostButtonText: {
      fontSize: 12,
      fontWeight: '800',
      color: theme.colors.white,
    },

    // ─── Trust Badges ─────────────────────────────────────────────────────
    trustRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 12,
      gap: 8,
    },
    trustBadge: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 5,
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      paddingVertical: 7,
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    trustText: {
      fontSize: 11,
      // Fixed: textBody → textSecondary
      color: theme.colors.textSecondary,
      fontWeight: '500',
    },

    // ─── CTA Bar ──────────────────────────────────────────────────────────
    ctaContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      paddingBottom: 28,
      backgroundColor: theme.colors.surface,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      gap: 12,
      ...Platform.select({
        android: { elevation: 16 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: -2 },
          shadowOpacity: 0.08,
          shadowRadius: 8,
        },
        web: {},
      }),
    },
    ctaInfo: { flex: 1 },
    ctaPlan: {
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    ctaPrice: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    ctaDuration: {
      fontSize: 11,
      color: theme.colors.textMuted,
    },
    ctaButton: {
      flex: 2,
      backgroundColor: theme.colors.primary,
      paddingVertical: 15,
      borderRadius: 30,
      alignItems: 'center',
      ...Platform.select({
        android: { elevation: 6 },
        ios: {
          shadowColor: theme.colors.primary,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.35,
          shadowRadius: 8,
        },
        web: {},
      }),
    },
    ctaButtonDisabled: {
      backgroundColor: theme.colors.textMuted,
      elevation: 0,
      shadowOpacity: 0,
    },
    ctaButtonText: {
      color: theme.colors.white,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.3,
    },

    checkoutOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: theme.colors.modalOverlay,
    },
    checkoutSheet: {
      backgroundColor: theme.colors.surfaceElevated,
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 28,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      ...Platform.select({
        android: { elevation: 12 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: -4 },
          shadowOpacity: 0.14,
          shadowRadius: 12,
        },
        web: {},
      }),
    },
    checkoutHandle: {
      width: 44,
      height: 4,
      borderRadius: 2,
      alignSelf: 'center',
      backgroundColor: theme.colors.divider,
      marginBottom: 14,
    },
    checkoutHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      marginBottom: 16,
    },
    checkoutHeaderCopy: {
      flex: 1,
    },
    checkoutTitle: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    checkoutSubtitle: {
      marginTop: 3,
      fontSize: 13,
      lineHeight: 19,
      color: theme.colors.textSecondary,
    },
    checkoutClose: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.backgroundLight,
    },
    checkoutPlanBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      borderRadius: 8,
      padding: 12,
      marginBottom: 14,
      backgroundColor: theme.colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    checkoutPlanLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.colors.textSecondary,
      textTransform: 'uppercase',
    },
    checkoutPlanName: {
      marginTop: 2,
      fontSize: 15,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    checkoutPlanPrice: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    checkoutOptionList: {
      gap: 10,
      marginBottom: 16,
    },
    checkoutOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderRadius: 8,
      padding: 12,
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    checkoutOptionActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primaryLight,
    },
    checkoutOptionIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.backgroundLight,
    },
    checkoutOptionCopy: {
      flex: 1,
    },
    checkoutOptionTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    checkoutOptionSub: {
      marginTop: 2,
      fontSize: 12,
      lineHeight: 17,
      color: theme.colors.textSecondary,
    },
    checkoutContinueButton: {
      minHeight: 48,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
    },
    checkoutContinueText: {
      color: theme.colors.white,
      fontSize: 15,
      fontWeight: '800',
    },

    // ─── Assisted ─────────────────────────────────────────────────────────
    planMonths: {
      fontSize: 13,
      fontWeight: '700',
      // Fixed: textBody → textSecondary
      color: theme.colors.textSecondary,
    },
    planMonthsActive: { color: theme.colors.primary },
    oldPrice: {
      fontSize: 11,
      textDecorationLine: 'line-through',
      color: theme.colors.textMuted,
      marginBottom: 6,
    },
    perMonthBadge: {
      backgroundColor: theme.colors.backgroundLight,
      borderRadius: 10,
      paddingHorizontal: 7,
      paddingVertical: 3,
    },
    perMonthText: {
      fontSize: 10,
      color: theme.colors.textSecondary,
      fontWeight: '600',
    },
    sectionLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
    },
    exclusivePill: {
      // Fixed: accentLight → primaryLight (safer on any theme)
      backgroundColor: theme.colors.primaryLight,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      paddingHorizontal: 12,
      paddingVertical: 4,
      marginRight: 10,
    },
    exclusivePillText: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.colors.accent,
      letterSpacing: 1,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: theme.colors.divider,
    },
    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      overflow: 'hidden',
      marginBottom: 20,
      ...Platform.select({
        android: { elevation: 2 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.06,
          shadowRadius: 6,
        },
        web: {},
      }),
    },
    cardTopAccent: {
      height: 4,
      backgroundColor: theme.colors.accent,
    },
    benefitRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingHorizontal: 16,
      paddingTop: 14,
      gap: 10,
    },
    benefitIcon: { fontSize: 18 },
    benefitText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      lineHeight: 21,
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: theme.colors.divider,
      marginHorizontal: 16,
      marginTop: 14,
    },
    pointsContainer: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    pointRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginVertical: 4,
      gap: 10,
    },
    pointDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
      marginTop: 6,
    },
    pointText: {
      flex: 1,
      fontSize: 13,
      // Fixed: textBody → textSecondary
      color: theme.colors.textSecondary,
      lineHeight: 20,
    },
    cardActions: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 14,
    },
    callbackBtn: {
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
      paddingVertical: 9,
      paddingHorizontal: 16,
      borderRadius: 20,
    },
    callbackText: {
      color: theme.colors.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    knowMoreText: {
      color: theme.colors.primary,
      fontWeight: '600',
      fontSize: 13,
    },
    offerBanner: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.primaryLight,
      borderRadius: 12,
      paddingVertical: 11,
      marginBottom: 16,
      gap: 8,
      borderWidth: 1,
      borderColor: theme.colors.primaryBorder,
    },
    offerEmoji: { fontSize: 16 },
    offerText: {
      fontSize: 13,
      fontWeight: '800',
      color: theme.colors.primary,
      letterSpacing: 0.5,
    },
    savingsRow: {
      backgroundColor: theme.colors.successLight,
      borderRadius: 12,
      padding: 12,
      marginBottom: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.success,
    },
    savingsText: {
      fontSize: 13,
      color: theme.colors.success,
      lineHeight: 19,
    },
  });
