import { Theme } from '@/core/theme/types';
import { StyleSheet } from 'react-native';

export const membershipStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.backgroundPage,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingBottom: 120,
    },

    // ─── Hero ─────────────────────────────────────────────────────────────
    heroCard: {
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      padding: 20,
      marginTop: 20,
      marginBottom: 20,
      overflow: 'hidden',
    },
    heroBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.colors.accent,
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      marginBottom: 12,
    },
    heroBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.colors.white,
      letterSpacing: 0.5,
    },
    heroTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: theme.colors.white,
      marginBottom: 4,
    },
    heroSubtitle: {
      fontSize: 13,
      color: theme.colors.accentLight,
      lineHeight: 19,
      marginBottom: 16,
    },
    heroStats: {
      flexDirection: 'row',
      gap: 12,
    },
    heroStat: {
      backgroundColor: theme.colors.accent,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 7,
      alignItems: 'center',
    },
    heroStatValue: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.colors.white,
    },
    heroStatLabel: {
      fontSize: 10,
      color: theme.colors.accentLight,
      marginTop: 1,
    },

    // ─── Tabs ─────────────────────────────────────────────────────────────
    tabs: {
      flexDirection: 'row',
      backgroundColor: theme.colors.backgroundLight,
      borderRadius: 12,
      padding: 4,
      marginBottom: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    tab: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      borderRadius: 9,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 6,
    },
    activeTab: {
      backgroundColor: theme.colors.white,
      elevation: 3,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    tabText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      fontWeight: '500',
    },
    activeTabText: {
      color: theme.colors.primary,
      fontWeight: '700',
    },

    // ─── Refund Banner ────────────────────────────────────────────────────
    refundBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.successLight,
      borderRadius: 12,
      padding: 12,
      marginBottom: 20,
      gap: 10,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.success,
    },
    refundIcon: { fontSize: 20 },
    refundText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.success,
    },
    refundSub: {
      fontSize: 11,
      color: theme.colors.success,
      marginTop: 1,
    },

    // ─── Plan Cards ───────────────────────────────────────────────────────
    planRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
      gap: 8,
    },
    planCard: {
      flex: 1,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      borderRadius: 16,
      padding: 12,
      alignItems: 'center',
      backgroundColor: theme.colors.white,
      position: 'relative',
      elevation: 1,
    },
    planCardActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primaryLight,
      elevation: 5,
    },
    popularBadge: {
      position: 'absolute',
      top: -11,
      backgroundColor: theme.colors.accent,
      paddingHorizontal: 9,
      paddingVertical: 3,
      borderRadius: 20,
    },
    popularBadgeText: {
      color: theme.colors.white,
      fontSize: 10,
      fontWeight: '700',
    },
    planName: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textBody,
      marginTop: 10,
    },
    planNameActive: { color: theme.colors.primary },
    planPrice: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      marginTop: 4,
    },
    planPriceActive: { color: theme.colors.primary },
    planDuration: {
      fontSize: 10,
      color: theme.colors.textMuted,
      marginBottom: 10,
    },
    radioOuter: {
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 2,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 4,
      marginBottom: 6,
    },
    radioOuterActive: { borderColor: theme.colors.primary },
    radioInner: {
      width: 9,
      height: 9,
      borderRadius: 5,
      backgroundColor: theme.colors.primary,
    },

    // ─── Feature Table ────────────────────────────────────────────────────
    featureTableCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      marginBottom: 20,
      elevation: 1,
    },
    featureTableHeader: {
      flexDirection: 'row',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderBottomWidth: 2,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primaryLight,
    },
    featureHeader: {
      flexDirection: 'row',
      paddingVertical: 10,
      borderBottomWidth: 2,
      borderColor: theme.colors.primary,
      marginBottom: 2,
    },
    featureHeaderLabel: {
      flex: 1,
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      paddingLeft: 0,
    },
    featureHeaderCol: {
      flex: 1,
      textAlign: 'center',
      fontSize: 11,
      color: theme.colors.textSecondary,
      fontWeight: '600',
    },
    featureHeaderColActive: {
      color: theme.colors.primary,
      fontWeight: '800',
    },
    featureTable: {
      borderRadius: 10,
      overflow: 'hidden',
      backgroundColor: theme.colors.white,
      borderWidth: 1,
      borderColor: theme.colors.divider,
      marginBottom: 20,
    },
    featureRow: {
      flexDirection: 'row',
      paddingVertical: 13,
      paddingHorizontal: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      alignItems: 'center',
    },
    featureRowLast: {
      borderBottomWidth: 0,
    },
    featureLabel: {
      flex: 1,
      fontSize: 13,
      color: theme.colors.textBody,
    },
    featureValues: {
      flexDirection: 'row',
      width: '45%',
      justifyContent: 'space-around',
    },
    featureCell: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 3,
      borderRadius: 6,
      marginHorizontal: 2,
    },
    featureCellActive: { backgroundColor: theme.colors.primaryLight },
    featureValue: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textBody,
      textAlign: 'center',
    },
    featureValueActive: { color: theme.colors.primary },
    featureCheck: { color: theme.colors.success },
    featureZero: { color: theme.colors.textMuted },

    // ─── Trust Badges ─────────────────────────────────────────────────────
    trustRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 12,
      gap: 8,
    },
    trustBadge: {
      flex: 1,
      backgroundColor: theme.colors.white,
      borderRadius: 20,
      paddingVertical: 7,
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      elevation: 1,
    },
    trustText: {
      fontSize: 11,
      color: theme.colors.textBody,
      fontWeight: '500',
    },

    // ─── CTA Bar ──────────────────────────────────────────────────────────
    ctaContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      paddingHorizontal: 16,
      paddingVertical: 12,
      paddingBottom: 28,
      backgroundColor: theme.colors.white,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      elevation: 16,
    },
    ctaInfo: { flex: 1 },
    ctaPlan: {
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    ctaPrice: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    ctaDuration: {
      fontSize: 11,
      color: theme.colors.textMuted,
    },
    ctaButton: {
      flex: 2,
      backgroundColor: theme.colors.primary,
      paddingVertical: 15,
      borderRadius: 30,
      alignItems: 'center',
      elevation: 6,
    },
    ctaButtonText: {
      color: theme.colors.white,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.3,
    },

    // ─── Assisted ─────────────────────────────────────────────────────────
    planMonths: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.textBody,
    },
    planMonthsActive: { color: theme.colors.primary },
    oldPrice: {
      fontSize: 11,
      textDecorationLine: 'line-through',
      color: theme.colors.textMuted,
      marginBottom: 6,
    },
    perMonthBadge: {
      backgroundColor: theme.colors.backgroundLight,
      borderRadius: 10,
      paddingHorizontal: 7,
      paddingVertical: 3,
    },
    perMonthText: {
      fontSize: 10,
      color: theme.colors.textSecondary,
      fontWeight: '600',
    },
    sectionLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
    },
    exclusivePill: {
      backgroundColor: theme.colors.accentLight,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      paddingHorizontal: 12,
      paddingVertical: 4,
      marginRight: 10,
    },
    exclusivePillText: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.colors.accent,
      letterSpacing: 1,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: theme.colors.divider,
    },
    card: {
      backgroundColor: theme.colors.white,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      overflow: 'hidden',
      marginBottom: 20,
      elevation: 2,
    },
    cardTopAccent: {
      height: 4,
      backgroundColor: theme.colors.accent,
    },
    benefitRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingHorizontal: 16,
      paddingTop: 14,
      gap: 10,
    },
    benefitIcon: { fontSize: 18 },
    benefitText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      lineHeight: 21,
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: theme.colors.divider,
      marginHorizontal: 16,
      marginTop: 14,
    },
    pointsContainer: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    pointRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginVertical: 4,
      gap: 10,
    },
    pointDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
      marginTop: 6,
    },
    pointText: {
      flex: 1,
      fontSize: 13,
      color: theme.colors.textBody,
      lineHeight: 20,
    },
    cardActions: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 14,
    },
    callbackBtn: {
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
      paddingVertical: 9,
      paddingHorizontal: 16,
      borderRadius: 20,
    },
    callbackText: {
      color: theme.colors.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    knowMoreText: {
      color: theme.colors.primary,
      fontWeight: '600',
      fontSize: 13,
    },
    offerBanner: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.primaryLight,
      borderRadius: 12,
      paddingVertical: 11,
      marginBottom: 16,
      gap: 8,
      borderWidth: 1,
      borderColor: theme.colors.primaryBorder,
    },
    offerEmoji: { fontSize: 16 },
    offerText: {
      fontSize: 13,
      fontWeight: '800',
      color: theme.colors.primary,
      letterSpacing: 0.5,
    },
    savingsRow: {
      backgroundColor: theme.colors.successLight,
      borderRadius: 12,
      padding: 12,
      marginBottom: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.success,
    },
    savingsText: {
      fontSize: 13,
      color: theme.colors.success,
      lineHeight: 19,
    },
    savingsHighlight: {
      fontWeight: '800',
    },
  });
