import { Theme } from '@/core/theme/types';
import { StyleSheet } from 'react-native';

export const forgotPasswordStyles = (theme: Theme) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: theme.colors.white,
    },
    container: { flex: 1 },
    scrollContent: {
      padding: 20,
      paddingTop: 32,
    },
    iconWrapper: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginBottom: 20,
    },
    title: {
      fontSize: 24,
      fontWeight: '900',
      color: theme.colors.textPrimary,
      marginBottom: 10,
      textAlign: 'center',
      fontFamily: 'clebri-bold',
    },
    subtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 21,
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.colors.errorLight,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.error,
    },
    errorBannerText: {
      color: theme.colors.error,
      fontSize: 13,
      flex: 1,
    },
    form: { marginTop: 4 },
    label: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
      marginBottom: 6,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 12,
      marginBottom: 4,
      minHeight: 50,
    },
    inputFocused: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.inputBackground,
    },
    inputIcon: { marginRight: 10 },
    input: {
      flex: 1,
      paddingVertical: 13,
      fontSize: 15,
      color: theme.colors.textPrimary,
    },
    inputError: {
      borderColor: theme.colors.error,
      backgroundColor: theme.colors.errorLight,
    },
    errorText: {
      color: theme.colors.error,
      fontSize: 12,
      marginBottom: 8,
      marginTop: 2,
    },
    primaryButton: {
      marginTop: 16,
      backgroundColor: theme.colors.primary,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 8,
    },
    primaryButtonText: {
      color: theme.colors.white,
      fontWeight: '700',
      fontSize: 16,
    },
    disabledButton: { opacity: 0.6 },
    backLink: {
      marginTop: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    backLinkText: {
      color: theme.colors.link,
      fontSize: 14,
      fontWeight: '600',
    },
    infoCard: {
      marginTop: 28,
      backgroundColor: theme.colors.primaryLight,
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.colors.primaryBorder,
    },
    infoCardTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.primary,
      marginBottom: 12,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 10,
    },
    infoIconWrapper: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: theme.colors.white,
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      flex: 1,
      lineHeight: 18,
    },
    successContainer: {
      flex: 1,
      padding: 24,
      justifyContent: 'center',
    },
    successIconWrapper: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginBottom: 24,
    },
    successTitle: {
      fontSize: 24,
      fontWeight: '900',
      color: theme.colors.textPrimary,
      marginBottom: 12,
      textAlign: 'center',
      fontFamily: 'clebri-bold',
    },
    successSubtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 22,
      marginBottom: 24,
    },
    successEmail: {
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    successTips: {
      width: '100%',
      backgroundColor: theme.colors.backgroundPage,
      borderRadius: 12,
      padding: 16,
      gap: 10,
      marginBottom: 28,
    },
    tipRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    tipText: {
      fontSize: 13,
      color: theme.colors.textMuted,
      flex: 1,
    },
    resendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      marginTop: 14,
    },
    resendText: {
      color: theme.colors.link,
      fontSize: 13,
      fontWeight: '500',
    },
  });
