import { StyleSheet, Platform } from 'react-native';
import { createBaseStyles } from '@/core/theme/baseStyles';
import { Theme } from '@/core/theme/types';

export const homeStyles = (
  theme: Theme,
  base: ReturnType<typeof createBaseStyles>
) =>
  StyleSheet.create({
    safe: StyleSheet.flatten(base.safe),
    dashboardContent: {
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 32,
      gap: 14,
    },
    heroPanel: {
      borderRadius: 8,
      padding: 16,
      gap: 16,
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    heroCopy: { gap: 6 },
    heroEyebrow: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    heroTitle: {
      color: theme.colors.textPrimary,
      fontSize: 23,
      fontWeight: '800',
      lineHeight: 29,
    },
    heroSubtitle: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 21,
    },
    heroButton: {
      minHeight: 46,
      borderRadius: 8,
      backgroundColor: theme.colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 14,
    },
    heroButtonText: {
      color: theme.colors.white,
      fontSize: 14,
      fontWeight: '800',
    },
    dashboardStatsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    dashboardStatCard: {
      width: '48.5%',
      minHeight: 94,
      borderRadius: 8,
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      padding: 12,
      justifyContent: 'space-between',
    },
    dashboardStatValue: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: '800',
    },
    dashboardStatLabel: {
      color: theme.colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    actionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    quickAction: {
      width: '48.5%',
      minHeight: 76,
      borderRadius: 8,
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      padding: 12,
      gap: 8,
    },
    quickActionIcon: {
      width: 32,
      height: 32,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
    },
    quickActionText: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      fontWeight: '800',
    },
    studentCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      padding: 12,
    },
    studentAvatar: {
      width: 42,
      height: 42,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
    },
    studentBody: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    studentName: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontWeight: '800',
    },
    studentMeta: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: '600',
    },
    studentSession: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: '700',
    },
    progressTrack: {
      height: 6,
      borderRadius: 3,
      overflow: 'hidden',
      backgroundColor: theme.colors.backgroundLight,
    },
    progressFill: {
      height: '100%',
      borderRadius: 3,
      backgroundColor: theme.colors.primary,
    },
    iconButton: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    guardCard: {
      flexDirection: 'row',
      gap: 12,
      borderRadius: 8,
      padding: 14,
      backgroundColor: theme.colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    guardCopy: { flex: 1, gap: 3 },
    guardTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    guardText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    listContent: {
      paddingBottom: 32,
    },
    listFooter: {
      paddingVertical: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },

    // ─── Stats ────────────────────────────────────────────────────────────
    statsRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 10,
      backgroundColor: theme.colors.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    statCard: {
      flex: 1,
      backgroundColor: theme.colors.primaryLight,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 8,
      alignItems: 'center',
      gap: 3,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    statValue: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    statLabel: {
      fontSize: 10,
      color: theme.colors.textMuted,
      fontWeight: '500',
      textAlign: 'center',
    },

    // ─── Section Header ───────────────────────────────────────────────────
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 10,
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    seeAllBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
    },
    seeAllText: {
      fontSize: 13,
      color: theme.colors.primary,
      fontWeight: '600',
    },

    // ─── Card ─────────────────────────────────────────────────────────────
    card: {
      backgroundColor: theme.colors.surface,
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      ...Platform.select({
        android: { elevation: 3 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.08,
          shadowRadius: 8,
        },
        web: {},
      }),
    },

    // ─── Photo ────────────────────────────────────────────────────────────
    photoWrapper: { position: 'relative' },
    photo: {
      width: '100%',
      height: 340,
    },
    photoScrim: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 96,
      backgroundColor: theme.colors.overlayDark,
      opacity: 0.48,
    },
    photoBadge: {
      position: 'absolute',
      top: 12,
      right: 12,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.overlayLight,
      borderRadius: 12,
      paddingHorizontal: 8,
      paddingVertical: 4,
      gap: 4,
    },
    photoBadgeText: {
      color: theme.colors.white,
      fontSize: 11,
      fontWeight: '600',
    },
    onlineBadge: {
      position: 'absolute',
      top: 12,
      left: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: theme.colors.overlayLight,
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: 20,
    },
    onlineDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.success,
    },
    onlineBadgeText: {
      color: theme.colors.white,
      fontSize: 11,
      fontWeight: '700',
    },
    newBadge: {
      position: 'absolute',
      left: 12,
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: 20,
    },
    newBadgeOnline: { top: 44 },
    newBadgeDefault: { top: 12 },
    newBadgeText: {
      color: theme.colors.white,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    photoOverlay: {
      position: 'absolute',
      bottom: 12,
      left: 14,
      right: 14,
    },
    heroName: {
      fontSize: 22,
      fontWeight: '800',
      color: theme.colors.white,
      marginBottom: 3,
      textShadowColor: theme.colors.overlayDark,
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 3,
    },
    heroLocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    heroLocation: {
      fontSize: 13,
      color: theme.colors.white,
      textShadowColor: theme.colors.overlayDark,
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },

    // ─── Card Content ─────────────────────────────────────────────────────
    cardContent: { padding: 14 },
    tagsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
      marginBottom: 12,
    },
    tag: {
      backgroundColor: theme.colors.primaryLight,
      paddingHorizontal: 11,
      paddingVertical: 5,
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    tagText: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: '600',
    },
    metaRow: {
      gap: 5,
      marginBottom: 14,
    },
    metaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    meta: {
      fontSize: 13,
      color: theme.colors.textSecondary,
    },
    divider: {
      height: 1,
      backgroundColor: theme.colors.divider,
      marginBottom: 14,
    },

    // ─── Actions ──────────────────────────────────────────────────────────
    actions: {
      flexDirection: 'row',
      gap: 10,
    },
    chatBtn: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: theme.colors.primary,
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    chatBtnPending: {
      backgroundColor: theme.colors.error,
    },
    chatText: {
      color: theme.colors.white,
      fontWeight: '700',
      fontSize: 14,
    },
    viewBtn: {
      flex: 1,
      flexDirection: 'row',
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    viewText: {
      color: theme.colors.primary,
      fontWeight: '700',
      fontSize: 14,
    },
    shortlistBtn: {
      width: 44,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
    },
    shortlistBtnActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },

    // ─── Empty ────────────────────────────────────────────────────────────
    emptyWrapper: {
      paddingVertical: 60,
      paddingHorizontal: 32,
      alignItems: 'center',
      gap: 12,
    },
    emptyIconWrapper: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    emptySub: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
  });
