import { createBaseStyles } from '@/core/theme/baseStyles';
import { Theme } from '@/core/theme/types';
import { Platform, StyleSheet } from 'react-native';

export const profileStyles = (
  theme: Theme,
  base: ReturnType<typeof createBaseStyles>
) =>
  StyleSheet.create({
    safe: StyleSheet.flatten(base.safe),
    container: StyleSheet.flatten(base.container),
    scrollContent: { paddingBottom: 10 },
    centerContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 32,
      gap: 12,
      backgroundColor: theme.colors.backgroundPage,
    },
    photo: {
      width: '100%',
      height: 320,
    },
    dotRow: {
      position: 'absolute',
      bottom: 12,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 6,
    },
    dot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.overlayDark,
    },
    dotActive: {
      backgroundColor: theme.colors.surface,
      width: 18,
    },
    nameCard: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    mentoraProfileHero: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      backgroundColor: theme.colors.surface,
      padding: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    mentoraAvatar: {
      width: 64,
      height: 64,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    mentoraHeroCopy: {
      flex: 1,
      minWidth: 0,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
    name: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      flex: 1,
      paddingRight: 12,
    },
    verificationBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 16,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderWidth: StyleSheet.hairlineWidth,
    },
    verificationBadgeVerified: {
      backgroundColor: theme.colors.successLight,
      borderColor: theme.colors.success,
    },
    verificationBadgeUnverified: {
      backgroundColor: theme.colors.primaryLight,
      borderColor: theme.colors.primaryBorder,
    },
    verificationBadgeText: {
      fontSize: 11,
      fontWeight: '700',
    },
    verificationBadgeTextVerified: { color: theme.colors.success },
    verificationBadgeTextUnverified: { color: theme.colors.primary },
    subText: {
      color: theme.colors.textMuted,
      fontSize: 14,
      marginBottom: 6,
    },
    locationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    locationText: {
      fontSize: 13,
      color: theme.colors.textMuted,
    },
    profileMetaGrid: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 14,
      paddingHorizontal: 16,
      paddingBottom: 4,
    },
    profileMetaItem: {
      flex: 1,
      minHeight: 58,
      borderRadius: 8,
      backgroundColor: theme.colors.backgroundLight,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      paddingVertical: 8,
    },
    profileMetaValue: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontWeight: '700',
      textAlign: 'center',
    },
    profileMetaLabel: {
      color: theme.colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
      marginTop: 2,
      textAlign: 'center',
    },
    section: { marginTop: 12 },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginBottom: 6,
      gap: 8,
    },
    sectionIconWrapper: {
      width: 24,
      height: 24,
      borderRadius: 6,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    card: {
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 4,
      ...Platform.select({
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.04,
          shadowRadius: 4,
        },
        android: { elevation: 1 },
        web: {},
      }),
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    rowLabel: {
      color: theme.colors.textMuted,
      fontSize: 14,
      flex: 1,
    },
    rowValue: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '500',
      flex: 2,
      textAlign: 'right',
    },
    aboutText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 22,
      paddingVertical: 10,
    },
    tagSection: {
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    tagSectionLabel: {
      fontSize: 12,
      color: theme.colors.textMuted,
      marginBottom: 8,
    },
    tagList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    tag: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: theme.colors.primaryLight,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    tagText: {
      fontSize: 13,
      color: theme.colors.primary,
      fontWeight: '500',
    },
    tagEmptyText: {
      color: theme.colors.textMuted,
      fontSize: 14,
      paddingVertical: 4,
    },
    videoIntroCard: {
      marginVertical: 10,
      borderRadius: 8,
      overflow: 'hidden',
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    videoIntroPreview: {
      width: '100%',
      aspectRatio: 16 / 9,
      backgroundColor: theme.colors.backgroundLight,
    },
    videoIntroThumbnail: {
      flex: 1,
      justifyContent: 'center',
    },
    videoIntroThumbnailImage: {
      resizeMode: 'cover',
    },
    videoIntroOverlay: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.overlayLight,
    },
    videoIntroPlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      backgroundColor: theme.colors.primaryLight,
    },
    videoIntroPlayButton: {
      width: 54,
      height: 54,
      borderRadius: 27,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
    },
    videoIntroPlaceholderText: {
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: '800',
    },
    videoIntroContent: {
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 5,
    },
    videoIntroTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    videoIntroTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    videoIntroSubtitle: {
      color: theme.colors.textMuted,
      fontSize: 12,
      lineHeight: 17,
    },
    videoIntroLocked: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      marginVertical: 8,
      opacity: 0.68,
      borderRadius: 8,
      backgroundColor: theme.colors.backgroundLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    videoIntroLockedIcon: {
      width: 38,
      height: 38,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
    },
    videoIntroLockedCopy: {
      flex: 1,
      minWidth: 0,
    },
    siblingList: { gap: 10, paddingBottom: 4 },
    siblingItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: theme.colors.backgroundLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    siblingIndex: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
    },
    siblingIndexText: {
      color: theme.colors.white,
      fontSize: 12,
      fontWeight: '800',
    },
    siblingContent: { flex: 1, gap: 2 },
    mentoraStudentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
    },
    mentoraStudentIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
    },
    mentoraStudentCopy: {
      flex: 1,
      minWidth: 0,
    },
    siblingTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '700',
    },
    siblingMeta: {
      color: theme.colors.textMuted,
      fontSize: 12,
      lineHeight: 17,
    },
    errorTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      marginTop: 8,
    },
    errorSubtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
    },
    retryButton: {
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 10,
      marginTop: 8,
    },
    retryButtonText: {
      color: theme.colors.white,
      fontWeight: '700',
      fontSize: 15,
    },
    mentoraActions: {
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 24,
    },
    mentoraActionButton: {
      minHeight: 52,
      borderRadius: 8,
      backgroundColor: theme.colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 14,
    },
    mentoraActionText: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    skeletonContainer: { flex: 1 },
    skeletonPhoto: {
      width: '100%',
      height: 320,
      backgroundColor: theme.colors.backgroundLight,
    },
    skeletonHeader: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      gap: 8,
    },
    skeletonCard: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      marginTop: 12,
      gap: 8,
    },
    skeletonLine: {
      height: 14,
      borderRadius: 7,
      backgroundColor: theme.colors.backgroundLight,
      width: '80%',
    },
    skeletonLineShort: { width: '50%' },
    footer: StyleSheet.flatten(base.footer),
    pdfActionBar: {
      flexDirection: 'row',
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 16,
      backgroundColor: theme.colors.surface,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.divider,
      ...Platform.select({
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: -2 },
          shadowOpacity: 0.06,
          shadowRadius: 8,
        },
        android: { elevation: 12 },
        web: {},
      }),
    },
    pdfActionButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 12,
    },
    pdfDownloadButton: { backgroundColor: theme.colors.primary },
    pdfShareButton: { backgroundColor: theme.colors.accent },
    pdfActionButtonDisabled: { opacity: 0.65 },
    pdfActionButtonText: {
      color: theme.colors.white,
      fontSize: 14,
      fontWeight: '700',
    },
  });
