export const COLLECTIONS = {
  USER: 'users',
  USER_SESSION: 'user_sessions',
  PROFILE: 'profiles',
  PREFERENCE: 'preferences',
  MEDIA: 'media',
  INTERACTION: 'interactions',
  PRIVACY_SETTING: 'privacy_settings',
  VERIFICATION: 'verification',
  USER_BLOCK: 'user_blocks',
  USER_REPORT: 'user_reports',
  PLAN: 'plans',
  FEATURE: 'features',
  PLAN_FEATURE: 'plan_features',
  SUBSCRIPTION: 'subscriptions',
  PAYMENT: 'payments',
  ANALYTICS_EVENT: 'analytics_events',
  MATCH: 'matches',
  CHAT_ROOM: 'chat_rooms',
  CHAT_MESSAGE: 'chat_messages',
  ACTIVITY_LOG: 'activity_logs',
  NOTIFICATION: 'notifications',
  NOTIFICATION_TEMPLATE: 'notification_templates',
  NOTIFICATION_LOG: 'notification_logs',
  USER_NOTIFICATION_SETTING: 'user_notification_settings',
};
