export enum ErrorCode {
  // AUTH
  INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS',
  INVALID_PASSWORD = 'AUTH.INVALID_PASSWORD',
  USER_NOT_FOUND = 'AUTH.USER_NOT_FOUND',
  TOKEN_EXPIRED = 'AUTH.TOKEN_EXPIRED',
  UNAUTHORIZED = 'AUTH.UNAUTHORIZED',

  // VALIDATION
  VALIDATION_FAILED = 'COMMON.VALIDATION_FAILED',

  // SERVER
  INTERNAL_ERROR = 'COMMON.INTERNAL_ERROR',
  ENDPOINT_NOT_FOUND = 'COMMON.ENDPOINT_NOT_FOUND',
}
