export enum SuccessCode {
  // =========================
  // AUTH
  // =========================
  AUTH_REGISTERED = 'AUTH.REGISTERED',
  AUTH_LOGIN_SUCCESS = 'AUTH.LOGIN_SUCCESS',
  AUTH_LOGOUT_SUCCESS = 'AUTH.LOGOUT_SUCCESS',
  AUTH_TOKEN_REFRESHED = 'AUTH.TOKEN_REFRESHED',
  AUTH_OTP_SENT = 'AUTH.OTP_SENT',
  AUTH_OTP_VERIFIED = 'AUTH.OTP_VERIFIED',
  AUTH_PASSWORD_RESET_SENT = 'AUTH.PASSWORD_RESET_SENT',
  AUTH_PASSWORD_RESET_SUCCESS = 'AUTH.PASSWORD_RESET_SUCCESS',
  AUTH_PASSWORD_CHANGED = 'AUTH.PASSWORD_CHANGED',
  AUTH_EMAIL_VERIFIED = 'AUTH.EMAIL_VERIFIED',
  AUTH_PHONE_VERIFIED = 'AUTH.PHONE_VERIFIED',
  AUTH_MAGIC_LINK_SENT = 'AUTH.MAGIC_LINK_SENT',
  AUTH_MAGIC_LINK_VERIFIED = 'AUTH.MAGIC_LINK_VERIFIED',

  // =========================
  // USER
  // =========================
  USER_FETCHED = 'USER.FETCHED',
  USER_UPDATED = 'USER.UPDATED',
  USER_DELETED = 'USER.DELETED',
  USER_STATUS_UPDATED = 'USER.STATUS_UPDATED',

  // =========================
  // PROFILE
  // =========================
  PROFILE_CREATED = 'PROFILE.CREATED',
  PROFILE_FETCHED = 'PROFILE.FETCHED',
  PROFILE_UPDATED = 'PROFILE.UPDATED',
  PROFILE_COMPLETED = 'PROFILE.COMPLETED',
  PROFILE_VERIFIED = 'PROFILE.VERIFIED',

  PROFILE_IMAGE_FETCHED = 'PROFILE.IMAGE_FETCHED',
  PROFILE_IMAGE_UPLOADED = 'PROFILE.IMAGE_UPLOADED',
  PROFILE_IMAGE_REORDERED = 'PROFILE.IMAGE_REORDERED',
  PROFILE_IMAGE_DELETED = 'PROFILE.IMAGE_DELETED',

  PROFILE_VIDEO_FETCHED = 'PROFILE.VIDEO_FETCHED',
  PROFILE_VIDEO_UPLOADED = 'PROFILE.VIDEO_UPLOADED',
  PROFILE_VIDEO_REORDERED = 'PROFILE.VIDEO_REORDERED',
  PROFILE_VIDEO_DELETED = 'PROFILE.VIDEO_DELETED',

  PROFILE_PRIVACY_SETTINGS_FETCHED = 'PROFILE.PRIVACY_SETTINGS_FETCHED',
  PROFILE_PRIVACY_SETTINGS_UPDATED = 'PROFILE.PRIVACY_SETTINGS_UPDATED',

  // =========================
  // PREFERENCES
  // =========================
  PREFERENCES_FETCHED = 'PREFERENCES.FETCHED',
  PREFERENCES_UPDATED = 'PREFERENCES.UPDATED',

  // =========================
  // SETTINGS
  // =========================
  SETTINGS_FETCHED = 'SETTINGS.FETCHED',
  SETTINGS_UPDATED = 'SETTINGS.UPDATED',
  SETTINGS_ACCOUNT_DEACTIVATED = 'SETTINGS.ACCOUNT_DEACTIVATED',
  SETTINGS_ACCOUNT_REACTIVATED = 'SETTINGS.ACCOUNT_REACTIVATED',
  SETTINGS_ACCOUNT_DELETION_SCHEDULED = 'SETTINGS.ACCOUNT_DELETION_SCHEDULED',
  SETTINGS_ACCOUNT_DELETION_CANCELLED = 'SETTINGS.ACCOUNT_DELETION_CANCELLED',
  SETTINGS_ACCOUNT_LINKED = 'SETTINGS.ACCOUNT_LINKED',
  SETTINGS_ACCOUNT_UNLINKED = 'SETTINGS.ACCOUNT_UNLINKED',
  SETTINGS_ACCOUNT_CHANGE_REQUESTED = 'SETTINGS.ACCOUNT_CHANGE_REQUESTED',
  SETTINGS_DEVICE_REVOKED = 'SETTINGS.DEVICE_REVOKED',
  SETTINGS_LOGIN_HISTORY_FETCHED = 'SETTINGS.LOGIN_HISTORY_FETCHED',

  // =========================
  // MATCHES
  // =========================
  MATCHES_FETCHED = 'MATCHES.FETCHED',
  MATCH_REQUEST_SENT = 'MATCH.REQUEST_SENT',
  MATCH_REQUEST_ACCEPTED = 'MATCH.REQUEST_ACCEPTED',
  MATCH_REQUEST_REJECTED = 'MATCH.REQUEST_REJECTED',
  MATCH_REMOVED = 'MATCH.REMOVED',
  MATCH_BLOCKED = 'MATCH.BLOCKED',
  MATCH_SHORTLISTED = 'MATCH.SHORTLISTED',
  MATCH_SHORTLIST_REMOVED = 'MATCH.SHORTLIST_REMOVED',

  // =========================
  // INTERESTS
  // =========================
  INTEREST_SENT = 'INTEREST.SENT',
  INTEREST_ACCEPTED = 'INTEREST.ACCEPTED',
  INTEREST_REJECTED = 'INTEREST.REJECTED',
  INTEREST_WITHDRAWN = 'INTEREST.WITHDRAWN',

  // =========================
  // CHAT
  // =========================
  CHAT_CREATED = 'CHAT.CREATED',
  CHAT_FETCHED = 'CHAT.FETCHED',
  CHAT_MESSAGE_SENT = 'CHAT.MESSAGE_SENT',
  CHAT_MESSAGE_DELETED = 'CHAT.MESSAGE_DELETED',
  CHAT_MESSAGE_READ = 'CHAT.MESSAGE_READ',

  // =========================
  // SEARCH
  // =========================
  SEARCH_RESULTS_FETCHED = 'SEARCH.RESULTS_FETCHED',
  SEARCH_FILTERS_APPLIED = 'SEARCH.FILTERS_APPLIED',

  // =========================
  // SUBSCRIPTION
  // =========================
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION.CREATED',
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION.ACTIVATED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION.RENEWED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION.CANCELLED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION.EXPIRED',
  SUBSCRIPTION_BILLING_FETCHED = 'SUBSCRIPTION.BILLING_FETCHED',

  // =========================
  // PAYMENT
  // =========================
  PAYMENT_CREATED = 'PAYMENT.CREATED',
  PAYMENT_SUCCESS = 'PAYMENT.SUCCESS',
  PAYMENT_VERIFIED = 'PAYMENT.VERIFIED',
  PAYMENT_FETCHED = 'PAYMENT.FETCHED',
  PAYMENTS_FETCHED = 'PAYMENTS.FETCHED',
  PAYMENT_FAILED_RECORDED = 'PAYMENT.FAILED_RECORDED',
  PAYMENT_REFUNDED = 'PAYMENT.REFUNDED',
  PAYMENT_WEBHOOK_PROCESSED = 'PAYMENT.WEBHOOK_PROCESSED',
  PAYMENT_INVOICE_FETCHED = 'PAYMENT.INVOICE_FETCHED',
  PAYMENT_GST_REPORT_FETCHED = 'PAYMENT.GST_REPORT_FETCHED',
  COUPON_VALIDATED = 'COUPON.VALIDATED',
  WALLET_FETCHED = 'WALLET.FETCHED',

  // =========================
  // REFERRALS
  // =========================
  REFERRALS_FETCHED = 'REFERRALS.FETCHED',
  REFERRAL_REWARD_EARNED = 'REFERRAL.REWARD_EARNED',

  // =========================
  // NOTIFICATION
  // =========================
  NOTIFICATION_FETCHED = 'NOTIFICATION.FETCHED',
  NOTIFICATION_READ = 'NOTIFICATION.READ',
  NOTIFICATION_ALL_READ = 'NOTIFICATION.ALL_READ',
  NOTIFICATION_DEVICE_TOKEN_REGISTERED = 'NOTIFICATION.DEVICE_TOKEN_REGISTERED',
  NOTIFICATION_DEVICE_TOKEN_REMOVED = 'NOTIFICATION.DEVICE_TOKEN_REMOVED',

  // =========================
  // SUPPORT
  // =========================
  SUPPORT_TICKET_CREATED = 'SUPPORT.TICKET_CREATED',
  SUPPORT_TICKET_FETCHED = 'SUPPORT.TICKET_FETCHED',
  SUPPORT_TICKETS_FETCHED = 'SUPPORT.TICKETS_FETCHED',
  SUPPORT_TICKET_REPLIED = 'SUPPORT.TICKET_REPLIED',
  SUPPORT_TICKET_UPDATED = 'SUPPORT.TICKET_UPDATED',
  SUPPORT_TICKET_CLOSED = 'SUPPORT.TICKET_CLOSED',

  // =========================
  // BLOCK / REPORT
  // =========================
  USER_BLOCKED = 'USER.BLOCKED',
  USER_UNBLOCKED = 'USER.UNBLOCKED',
  USER_REPORTED = 'USER.REPORTED',

  // =========================
  // ADMIN
  // =========================
  ADMIN_USER_VERIFIED = 'ADMIN.USER_VERIFIED',
  ADMIN_PROFILE_APPROVED = 'ADMIN.PROFILE_APPROVED',
  ADMIN_PROFILE_REJECTED = 'ADMIN.PROFILE_REJECTED',
  ADMIN_USERS_FETCHED = 'ADMIN.USERS_FETCHED',
  ADMIN_USER_FETCHED = 'ADMIN.USER_FETCHED',
  ADMIN_USER_UPDATED = 'ADMIN.USER_UPDATED',
  ADMIN_BROADCAST_SENT = 'ADMIN.BROADCAST_SENT',
  ADMIN_PERMISSION_CREATED = 'ADMIN.PERMISSION_CREATED',
  ADMIN_PERMISSIONS_FETCHED = 'ADMIN.PERMISSIONS_FETCHED',
  ADMIN_PERMISSION_DELETED = 'ADMIN.PERMISSION_DELETED',
  ADMIN_ROLE_CREATED = 'ADMIN.ROLE_CREATED',
  ADMIN_ROLES_FETCHED = 'ADMIN.ROLES_FETCHED',
  ADMIN_ROLE_UPDATED = 'ADMIN.ROLE_UPDATED',
  ADMIN_ROLE_DELETED = 'ADMIN.ROLE_DELETED',
  ADMIN_USER_ROLES_FETCHED = 'ADMIN.USER_ROLES_FETCHED',
  ADMIN_USER_ROLES_UPDATED = 'ADMIN.USER_ROLES_UPDATED',
  ADMIN_AUDIT_LOGS_FETCHED = 'ADMIN.AUDIT_LOGS_FETCHED',
  ADMIN_MODERATION_QUEUE_FETCHED = 'ADMIN.MODERATION_QUEUE_FETCHED',
  ADMIN_DASHBOARD_FETCHED = 'ADMIN.DASHBOARD_FETCHED',

  // =========================
  // PLANS / FEATURES
  // =========================
  PLANS_FETCHED = 'PLANS.FETCHED',
  PLAN_FETCHED = 'PLAN.FETCHED',
  PLAN_CREATED = 'PLAN.CREATED',
  PLAN_UPDATED = 'PLAN.UPDATED',
  FEATURES_FETCHED = 'FEATURES.FETCHED',
  FEATURE_CREATED = 'FEATURE.CREATED',
  FEATURE_ASSIGNED = 'FEATURE.ASSIGNED',
  FEATURE_REMOVED = 'FEATURE.REMOVED',

  // =========================
  // ANALYTICS
  // =========================
  ANALYTICS_TRACKED = 'ANALYTICS.TRACKED',
  ANALYTICS_FETCHED = 'ANALYTICS.FETCHED',

  // =========================
  // FILES
  // =========================
  FILE_UPLOADED = 'FILE.UPLOADED',
  FILE_DELETED = 'FILE.DELETED',

  // =========================
  // GENERIC
  // =========================
  SUCCESS = 'SUCCESS',
}
