export enum SuccessCode {
  // =========================
  // AUTH
  // =========================
  AUTH_REGISTERED = 'AUTH.REGISTERED',
  AUTH_LOGIN_SUCCESS = 'AUTH.LOGIN_SUCCESS',
  AUTH_LOGOUT_SUCCESS = 'AUTH.LOGOUT_SUCCESS',
  AUTH_TOKEN_REFRESHED = 'AUTH.TOKEN_REFRESHED',
  AUTH_OTP_SENT = 'AUTH.OTP_SENT',
  AUTH_OTP_VERIFIED = 'AUTH.OTP_VERIFIED',
  AUTH_PASSWORD_RESET_SENT = 'AUTH.PASSWORD_RESET_SENT',
  AUTH_PASSWORD_RESET_SUCCESS = 'AUTH.PASSWORD_RESET_SUCCESS',
  AUTH_PASSWORD_CHANGED = 'AUTH.PASSWORD_CHANGED',
  AUTH_EMAIL_VERIFIED = 'AUTH.EMAIL_VERIFIED',
  AUTH_PHONE_VERIFIED = 'AUTH.PHONE_VERIFIED',

  // =========================
  // USER
  // =========================
  USER_FETCHED = 'USER.FETCHED',
  USER_UPDATED = 'USER.UPDATED',
  USER_DELETED = 'USER.DELETED',
  USER_STATUS_UPDATED = 'USER.STATUS_UPDATED',

  // =========================
  // PROFILE
  // =========================
  PROFILE_CREATED = 'PROFILE.CREATED',
  PROFILE_FETCHED = 'PROFILE.FETCHED',
  PROFILE_UPDATED = 'PROFILE.UPDATED',
  PROFILE_COMPLETED = 'PROFILE.COMPLETED',
  PROFILE_VERIFIED = 'PROFILE.VERIFIED',

  PROFILE_IMAGE_FETCHED = 'PROFILE.IMAGE_FETCHED',
  PROFILE_IMAGE_UPLOADED = 'PROFILE.IMAGE_UPLOADED',
  PROFILE_IMAGE_REORDERED = 'PROFILE.IMAGE_REORDERED',
  PROFILE_IMAGE_DELETED = 'PROFILE.IMAGE_DELETED',

  PROFILE_VIDEO_FETCHED = 'PROFILE.VIDEO_FETCHED',
  PROFILE_VIDEO_UPLOADED = 'PROFILE.VIDEO_UPLOADED',
  PROFILE_VIDEO_REORDERED = 'PROFILE.VIDEO_REORDERED',
  PROFILE_VIDEO_DELETED = 'PROFILE.VIDEO_DELETED',

  PROFILE_PRIVACY_SETTINGS_FETCHED = 'PROFILE.PRIVACY_SETTINGS_FETCHED',
  PROFILE_PRIVACY_SETTINGS_UPDATED = 'PROFILE.PRIVACY_SETTINGS_UPDATED',

  // =========================
  // PREFERENCES
  // =========================
  PREFERENCES_FETCHED = 'PREFERENCES.FETCHED',
  PREFERENCES_UPDATED = 'PREFERENCES.UPDATED',

  // =========================
  // MATCHES
  // =========================
  MATCHES_FETCHED = 'MATCHES.FETCHED',
  MATCH_REQUEST_SENT = 'MATCH.REQUEST_SENT',
  MATCH_REQUEST_ACCEPTED = 'MATCH.REQUEST_ACCEPTED',
  MATCH_REQUEST_REJECTED = 'MATCH.REQUEST_REJECTED',
  MATCH_REMOVED = 'MATCH.REMOVED',
  MATCH_BLOCKED = 'MATCH.BLOCKED',

  // =========================
  // INTERESTS
  // =========================
  INTEREST_SENT = 'INTEREST.SENT',
  INTEREST_ACCEPTED = 'INTEREST.ACCEPTED',
  INTEREST_REJECTED = 'INTEREST.REJECTED',
  INTEREST_WITHDRAWN = 'INTEREST.WITHDRAWN',

  // =========================
  // CHAT
  // =========================
  CHAT_CREATED = 'CHAT.CREATED',
  CHAT_FETCHED = 'CHAT.FETCHED',
  CHAT_MESSAGE_SENT = 'CHAT.MESSAGE_SENT',
  CHAT_MESSAGE_DELETED = 'CHAT.MESSAGE_DELETED',
  CHAT_MESSAGE_READ = 'CHAT.MESSAGE_READ',

  // =========================
  // SEARCH
  // =========================
  SEARCH_RESULTS_FETCHED = 'SEARCH.RESULTS_FETCHED',
  SEARCH_FILTERS_APPLIED = 'SEARCH.FILTERS_APPLIED',

  // =========================
  // SUBSCRIPTION
  // =========================
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION.CREATED',
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION.ACTIVATED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION.RENEWED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION.CANCELLED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION.EXPIRED',

  // =========================
  // PAYMENT
  // =========================
  PAYMENT_CREATED = 'PAYMENT.CREATED',
  PAYMENT_SUCCESS = 'PAYMENT.SUCCESS',
  PAYMENT_VERIFIED = 'PAYMENT.VERIFIED',
  PAYMENT_REFUNDED = 'PAYMENT.REFUNDED',

  // =========================
  // NOTIFICATION
  // =========================
  NOTIFICATION_FETCHED = 'NOTIFICATION.FETCHED',
  NOTIFICATION_READ = 'NOTIFICATION.READ',
  NOTIFICATION_ALL_READ = 'NOTIFICATION.ALL_READ',

  // =========================
  // BLOCK / REPORT
  // =========================
  USER_BLOCKED = 'USER.BLOCKED',
  USER_UNBLOCKED = 'USER.UNBLOCKED',
  USER_REPORTED = 'USER.REPORTED',

  // =========================
  // ADMIN
  // =========================
  ADMIN_USER_VERIFIED = 'ADMIN.USER_VERIFIED',
  ADMIN_PROFILE_APPROVED = 'ADMIN.PROFILE_APPROVED',
  ADMIN_PROFILE_REJECTED = 'ADMIN.PROFILE_REJECTED',

  // =========================
  // FILES
  // =========================
  FILE_UPLOADED = 'FILE.UPLOADED',
  FILE_DELETED = 'FILE.DELETED',

  // =========================
  // GENERIC
  // =========================
  SUCCESS = 'SUCCESS',
}
