export enum AnalyticsEventType {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  PROFILE_VIEWED = 'PROFILE_VIEWED',
  MATCH_REQUEST_SENT = 'MATCH_REQUEST_SENT',
  MATCH_ACCEPTED = 'MATCH_ACCEPTED',
  CHAT_STARTED = 'CHAT_STARTED',
  SUBSCRIPTION_PURCHASED = 'SUBSCRIPTION_PURCHASED',
}
