import { createBaseStyles } from '@/core/theme/baseStyles';
import { Theme } from '@/core/theme/types';
import { Platform, StyleSheet } from 'react-native';

export const matchListStyles = (
  theme: Theme,
  base: ReturnType<typeof createBaseStyles>
) =>
  StyleSheet.create({
    safe: StyleSheet.flatten(base.safe),
    listContent: {
      paddingBottom: 32,
    },
    listFooter: {
      paddingVertical: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },

    // ─── Tabs ─────────────────────────────────────────────────────────────
    tabsWrapper: {
      backgroundColor: theme.colors.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    tabsScroll: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      gap: 8,
    },
    tab: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundLight,
    },
    tabActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    tabText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    tabTextActive: { color: theme.colors.white },
    tabBadge: {
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.colors.primaryLight,
      paddingHorizontal: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabBadgeActive: { backgroundColor: theme.colors.overlayDark },
    tabBadgeText: {
      fontSize: 10,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    tabBadgeTextActive: { color: theme.colors.white },

    // ─── Toolbar ──────────────────────────────────────────────────────────
    matchToolbar: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: theme.colors.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.divider,
      marginBottom: 12,
    },
    matchToolbarRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    // Fixed: replaces incorrect styles.safe usage in MatchListToolbar
    matchToolbarLeft: {
      flex: 1,
    },
    matchToolbarTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    matchToolbarSubtitle: {
      marginTop: 4,
      fontSize: 12,
      color: theme.colors.textMuted,
    },
    hasFilterContainer: {
      marginTop: 6,
      flexDirection: 'row',
      alignItems: 'center',
    },
    hasFilterContent: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.primaryLight,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      gap: 6,
    },
    hasFilterText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.primary,
    },
    clearFilterBtn: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: theme.colors.backgroundLight,
    },
    clearFilterBtnText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.textSecondary,
    },

    // ─── Card ─────────────────────────────────────────────────────────────
    card: {
      backgroundColor: theme.colors.surface,
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      ...Platform.select({
        android: { elevation: 3 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.07,
          shadowRadius: 8,
        },
        web: {},
      }),
    },
    photo: { width: '100%', height: 300 },
    photoWrapper: { position: 'relative' },
    photoScrim: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 90,
      backgroundColor: theme.colors.overlayDark,
      opacity: 0.48,
    },
    badgeRow: {
      position: 'absolute',
      top: 12,
      left: 12,
      flexDirection: 'row',
      gap: 6,
    },
    newBadge: {
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    newBadgeText: {
      color: theme.colors.white,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    curatedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.accent,
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 4,
      gap: 5,
    },
    curatedBadgeText: {
      color: theme.colors.white,
      fontSize: 10,
      fontWeight: '800',
    },
    onlineBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.overlayDark,
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 4,
      gap: 5,
    },
    onlineDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.success,
    },
    onlineBadgeText: {
      color: theme.colors.white,
      fontSize: 11,
      fontWeight: '600',
    },
    nameOverlay: {
      position: 'absolute',
      bottom: 12,
      left: 14,
      right: 14,
    },
    nameOverlayText: {
      color: theme.colors.white,
      fontSize: 22,
      fontWeight: '800',
      marginBottom: 3,
      textShadowColor: theme.colors.overlayDark,
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 3,
    },
    locationOverlayRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    locationOverlayText: {
      color: theme.colors.white,
      fontSize: 13,
      textShadowColor: theme.colors.overlayDark,
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    info: { padding: 14 },
    tagsRow: {
      flexDirection: 'row',
      gap: 7,
      flexWrap: 'wrap',
      marginBottom: 12,
    },
    tag: {
      backgroundColor: theme.colors.primaryLight,
      paddingHorizontal: 11,
      paddingVertical: 5,
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    tagText: { color: theme.colors.primary, fontSize: 12, fontWeight: '600' },
    metaRow: { gap: 5, marginBottom: 14 },
    metaItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    metaText: { color: theme.colors.textSecondary, fontSize: 13, flex: 1 },
    curatorNote: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      padding: 10,
      marginBottom: 14,
      borderRadius: 12,
      backgroundColor: theme.colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    curatorNoteText: {
      flex: 1,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600',
    },
    actions: { flexDirection: 'row', gap: 10 },
    outlineBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
      borderRadius: 12,
      paddingVertical: 12,
    },
    outlineText: {
      color: theme.colors.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    primaryBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      paddingVertical: 12,
    },
    primaryBtnRequest: {
      flex: 1.25,
      shadowColor: theme.colors.success,
      shadowOpacity: 0.18,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    primaryBtnPending: { backgroundColor: theme.colors.error },
    primaryBtnSuccess: { backgroundColor: theme.colors.success },
    primaryBtnAccept: { backgroundColor: theme.colors.success },
    primaryText: { color: theme.colors.white, fontWeight: '700', fontSize: 13 },
    rejectIconBtn: {
      width: 44,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.colors.error,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
    },
    rejectBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderColor: theme.colors.error,
      borderRadius: 12,
      paddingVertical: 12,
      backgroundColor: theme.colors.surface,
    },
    rejectText: {
      color: theme.colors.error,
      fontWeight: '700',
      fontSize: 13,
    },
    shortlistBtn: {
      width: 44,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
    },
    shortlistBtnActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },

    // ─── Skeleton ─────────────────────────────────────────────────────────
    skeletonCard: {
      backgroundColor: theme.colors.surface,
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    skeletonPhoto: {
      width: '100%',
      height: 300,
      backgroundColor: theme.colors.backgroundLight,
    },
    skeletonInfo: { padding: 14, gap: 10 },
    skeletonLine: {
      height: 13,
      borderRadius: 6,
      backgroundColor: theme.colors.backgroundLight,
    },
    skeletonLineShort: { width: '55%' },
    skeletonLineXShort: { width: '35%' },

    // ─── Empty ────────────────────────────────────────────────────────────
    emptyContainer: {
      paddingVertical: 60,
      paddingHorizontal: 32,
      alignItems: 'center',
      gap: 12,
    },
    emptyIconWrapper: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },

    // ─── Match Success Modal ─────────────────────────────────────────────
    matchSuccessOverlay: {
      flex: 1,
      backgroundColor: theme.colors.overlayDark,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    matchSuccessSheet: {
      width: '100%',
      maxWidth: 380,
      backgroundColor: theme.colors.surface,
      borderRadius: 24,
      paddingHorizontal: 22,
      paddingVertical: 24,
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      ...Platform.select({
        android: { elevation: 10 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.2,
          shadowRadius: 26,
        },
        web: {
          boxShadow: `0px 16px 42px ${theme.colors.black}2E`,
        },
      }),
    },
    matchSuccessBadge: {
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
      marginBottom: 14,
    },
    matchSuccessTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    matchSuccessMessage: {
      marginTop: 8,
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'center',
      color: theme.colors.textSecondary,
      marginBottom: 18,
    },
    matchSuccessPhotosRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 22,
    },
    matchSuccessPhoto: {
      width: 74,
      height: 74,
      borderRadius: 37,
      borderWidth: 2,
      borderColor: theme.colors.primaryLight,
      backgroundColor: theme.colors.backgroundLight,
    },
    matchSuccessConnector: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
      marginHorizontal: -10,
      zIndex: 1,
      borderWidth: 1,
      borderColor: theme.colors.primaryBorder,
    },
    matchSuccessPrimaryCta: {
      width: '100%',
      minHeight: 50,
      borderRadius: 14,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      marginBottom: 10,
    },
    matchSuccessPrimaryText: {
      color: theme.colors.white,
      fontSize: 14,
      fontWeight: '800',
    },
    matchSuccessSecondaryCta: {
      width: '100%',
      minHeight: 48,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
    },
    matchSuccessSecondaryText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '700',
    },

    // ─── Filter Modal ─────────────────────────────────────────────────────
    filterModalOverlay: {
      flex: 1,
      backgroundColor: theme.colors.overlayDark,
      justifyContent: Platform.OS === 'web' ? 'center' : 'flex-end',
      alignItems: Platform.OS === 'web' ? 'center' : 'stretch',
      paddingHorizontal: Platform.OS === 'web' ? 16 : 0,
      paddingVertical: Platform.OS === 'web' ? 24 : 0,
    },
    filterModalSheet: {
      width: Platform.OS === 'web' ? '100%' : undefined,
      maxWidth: Platform.OS === 'web' ? 430 : undefined,
      maxHeight: Platform.OS === 'web' ? '88%' : '90%',
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: Platform.OS === 'web' ? 22 : 28,
      borderTopRightRadius: Platform.OS === 'web' ? 22 : 28,
      borderBottomLeftRadius: Platform.OS === 'web' ? 22 : 0,
      borderBottomRightRadius: Platform.OS === 'web' ? 22 : 0,
      borderWidth: Platform.OS === 'web' ? StyleSheet.hairlineWidth : 0,
      borderColor: theme.colors.divider,
      overflow: 'hidden',
      paddingTop: 12,
      paddingHorizontal: 16,
      paddingBottom: 22,
      ...Platform.select({
        android: { elevation: 12 },
        ios: {
          shadowColor: theme.colors.black,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.18,
          shadowRadius: 24,
        },
        web: {
          boxShadow: `0px 18px 50px ${theme.colors.black}33`,
        },
      }),
    },
    // Fixed: borderStrong → border
    filterModalHandle: {
      width: 46,
      height: 5,
      borderRadius: 99,
      backgroundColor: theme.colors.border,
      alignSelf: 'center',
      marginBottom: 16,
      ...Platform.select({
        web: {
          display: 'none',
        },
      }),
    },
    filterModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 18,
    },
    filterModalBody: {
      flexGrow: 1,
      flexShrink: 1,
    },
    filterModalScrollContent: {
      paddingBottom: 12,
    },
    filterModalTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    filterModalSubtitle: {
      marginTop: 3,
      fontSize: 13,
      color: theme.colors.textMuted,
    },
    filterCloseBtn: {
      width: 38,
      height: 38,
      borderRadius: 12,
      backgroundColor: theme.colors.backgroundLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterSearchBox: {
      height: 50,
      borderRadius: 16,
      backgroundColor: theme.colors.backgroundLight,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      gap: 10,
      marginBottom: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    filterSearchInput: {
      flex: 1,
      fontSize: 15,
      color: theme.colors.textPrimary,
      paddingVertical: 0,
    },
    filterQuickToggleGroup: {
      gap: 10,
      marginBottom: 10,
    },
    filterQuickToggle: {
      minHeight: 46,
      borderRadius: 16,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    filterQuickToggleActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primaryLight,
    },
    filterQuickToggleText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      color: theme.colors.textSecondary,
    },
    filterQuickToggleTextActive: { color: theme.colors.primary },
    filterModalFooter: {
      flexDirection: 'row',
      gap: 12,
      paddingTop: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.divider,
    },
    filterClearButton: {
      flex: 1,
      height: 52,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterClearButtonText: {
      color: theme.colors.textPrimary,
      fontWeight: '800',
      fontSize: 14,
    },
    filterApplyButton: {
      flex: 1.35,
      height: 52,
      borderRadius: 16,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterApplyButtonText: {
      color: theme.colors.white,
      fontWeight: '800',
      fontSize: 14,
    },
    filterSectionContainer: { marginBottom: 22 },
    filterSectionTitle: {
      marginBottom: 10,
      fontSize: 15,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    filterOptionsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    filterOptionButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    filterOptionButtonSelected: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
    },
    filterOptionButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    filterOptionButtonTextSelected: { color: theme.colors.white },
  });
