import { Theme } from '@/core/theme/types';
import { Platform, StyleSheet } from 'react-native';

export const matchListStyles = (theme: Theme) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: theme.colors.backgroundPage,
    },
    listContent: {
      paddingBottom: 32,
    },

    // ─── Tabs ─────────────────────────────────────────────────────────────
    tabsWrapper: {
      backgroundColor: theme.colors.white,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    tabsScroll: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      gap: 8,
    },
    tab: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundLight,
    },
    tabActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    tabText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    tabTextActive: {
      color: theme.colors.white,
    },
    tabBadge: {
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.colors.primaryLight,
      paddingHorizontal: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabBadgeActive: {
      backgroundColor: theme.colors.accentLight,
    },
    tabBadgeText: {
      fontSize: 10,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    tabBadgeTextActive: {
      color: theme.colors.white,
    },

    // ─── Search ───────────────────────────────────────────────────────────
    searchWrapper: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 14,
      backgroundColor: theme.colors.white,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      marginBottom: 12,
    },
    searchHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 10,
    },
    searchBox: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      gap: 8,
      backgroundColor: theme.colors.backgroundLight,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      height: 42,
    },
    filterToggle: {
      width: 42,
      height: 42,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.white,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterToggleActive: {
      backgroundColor: theme.colors.primary,
    },
    filterCountBadge: {
      position: 'absolute',
      top: -6,
      right: -6,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      paddingHorizontal: 4,
      backgroundColor: theme.colors.error,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: theme.colors.white,
    },
    filterCountText: {
      color: theme.colors.white,
      fontSize: 10,
      fontWeight: '800',
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.textPrimary,
    },

    // ─── Results Bar ──────────────────────────────────────────────────────
    resultsBarCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    clearFiltersText: {
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: '700',
    },
    filterPanel: {
      gap: 14,
      padding: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.white,
    },
    filterPanelHeader: {
      gap: 3,
    },
    filterPanelTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    filterPanelSubtitle: {
      color: theme.colors.textMuted,
      fontSize: 12,
    },
    filterSection: {
      gap: 8,
    },
    filterInputBox: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 46,
      paddingHorizontal: 12,
      gap: 8,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.white,
    },
    filterLabel: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      fontWeight: '700',
    },
    filterChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    filterChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.white,
    },
    filterChipActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    filterChipText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: '700',
    },
    filterChipTextActive: {
      color: theme.colors.white,
    },
    verifiedToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.white,
    },
    verifiedToggleActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    verifiedToggleText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: '700',
    },
    verifiedToggleTextActive: {
      color: theme.colors.white,
    },
    resultsBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    resultsText: {
      fontSize: 13,
      color: theme.colors.textMuted,
      fontWeight: '500',
    },
    resultsHighlight: {
      color: theme.colors.primary,
      fontWeight: '700',
    },

    // ─── Card ─────────────────────────────────────────────────────────────
    card: {
      backgroundColor: theme.colors.white,
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
      ...Platform.select({ android: { elevation: 3 } }),
    },
    photo: { width: '100%', height: 300 },
    photoWrapper: { position: 'relative' },
    photoScrim: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 140,
      backgroundColor: theme.colors.overlayDark,
    },
    badgeRow: {
      position: 'absolute',
      top: 12,
      left: 12,
      flexDirection: 'row',
      gap: 6,
    },
    newBadge: {
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    newBadgeText: {
      color: theme.colors.white,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    onlineBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.black,
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 4,
      gap: 5,
    },
    onlineDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.success,
    },
    onlineBadgeText: {
      color: theme.colors.white,
      fontSize: 11,
      fontWeight: '600',
    },
    nameOverlay: {
      position: 'absolute',
      bottom: 12,
      left: 14,
      right: 14,
    },
    nameOverlayText: {
      color: theme.colors.white,
      fontSize: 22,
      fontWeight: '800',
      marginBottom: 3,
    },
    locationOverlayRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    locationOverlayText: {
      color: theme.colors.accentLight,
      fontSize: 13,
    },
    info: {
      padding: 14,
    },
    tagsRow: {
      flexDirection: 'row',
      gap: 7,
      flexWrap: 'wrap',
      marginBottom: 12,
    },
    tag: {
      backgroundColor: theme.colors.primaryLight,
      paddingHorizontal: 11,
      paddingVertical: 5,
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.primaryBorder,
    },
    tagText: { color: theme.colors.primary, fontSize: 12, fontWeight: '600' },
    metaRow: { gap: 5, marginBottom: 14 },
    metaItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    metaText: { color: theme.colors.textSecondary, fontSize: 13 },
    actions: { flexDirection: 'row', gap: 10 },
    outlineBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
      borderRadius: 12,
      paddingVertical: 12,
    },
    outlineText: {
      color: theme.colors.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    primaryBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      paddingVertical: 12,
      elevation: 3,
    },
    primaryBtnPending: {
      backgroundColor: theme.colors.error,
    },
    primaryBtnSuccess: {
      backgroundColor: theme.colors.success,
    },
    primaryText: { color: theme.colors.white, fontWeight: '700', fontSize: 13 },
    shortlistBtn: {
      width: 44,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.accentLight,
    },
    shortlistBtnActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },

    // ─── Skeleton ─────────────────────────────────────────────────────────
    skeletonCard: {
      backgroundColor: theme.colors.white,
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.divider,
    },
    skeletonPhoto: {
      width: '100%',
      height: 300,
      backgroundColor: theme.colors.backgroundLight,
    },
    skeletonInfo: { padding: 14, gap: 10 },
    skeletonLine: {
      height: 13,
      borderRadius: 6,
      backgroundColor: theme.colors.backgroundLight,
    },
    skeletonLineShort: { width: '55%' },
    skeletonLineXShort: { width: '35%' },
    listFooter: {
      paddingVertical: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },

    // ─── Empty ────────────────────────────────────────────────────────────
    emptyContainer: {
      paddingVertical: 60,
      paddingHorizontal: 32,
      alignItems: 'center',
      gap: 12,
    },
    emptyIconWrapper: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: 14,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
    emptyBtn: {
      marginTop: 8,
      paddingHorizontal: 24,
      paddingVertical: 11,
      borderRadius: 24,
      backgroundColor: theme.colors.primary,
    },
    emptyBtnText: {
      color: theme.colors.white,
      fontWeight: '700',
      fontSize: 14,
    },
  });
